## Topic Modelling Newspapers

We are going to use this notebook to topic model our newspaper corpus. We start by setting up our imports.

In [1]:
import gensim

C:\Users\redab\Anaconda3\lib\site-packages\gensim\utils.py:1212: UserWarning: detected Windows; aliasing chunkize to chunkize_serial
  warnings.warn("detected Windows; aliasing chunkize to chunkize_serial")


In [2]:
import spacy
import os

In [3]:
import xml.etree.ElementTree as ET

### Accessing xml files

In the following lines of code, we are going to assemble the important information from the xml files. The following lines of code iterates through every XML file and accesses it. But we only add it to our corpus if it is censorship related. The following method identifies this.

In [4]:
# corpus = {}

In [5]:
def is_censorship(text):
    # finds out whether censorship or not; for each additional word we wish to add to constrain our group,
    # we add 'or "word" in text' before the final colon in the immediate line below
    if "censor" in text or "censorship" in text:
        return True
    else:
        return False

In [6]:
is_censorship("censor censorship suppress ban") # Here we can display individual texts in order to see if they fit within our 'is_censorship' group as defined above

True

In [ ]:
len(files)

In [ ]:
2 + 3

In [7]:
texts = [] # We are creating a list called "text"

In [8]:
i = 0 # Here we include the entire NYT database in our corpus
files = {}
for folder in os.listdir("NYT"):
    for filename in os.listdir("NYT/" + folder):
        if filename.endswith(".xml"):
            tree = ET.parse("NYT/" + folder + "/" +filename)
            root = tree.getroot()
            try:
                if is_censorship(root[-1].text):
                    files[filename] = []
                    files[filename].append(root[-1].text)
                    files[filename].append(root[3].text)
                    files[filename].append(root[4].text)
                    # add it to corpus
            except IndexError:
                continue

In [9]:
# i = 0 # Here we selectively add folders to our corpus
# files = {}
# folders = ["NYT/sm_55428_1004/","NYT/sm_55428_1005/"]
# for folder in folders:
#     for filename in os.listdir(folder):
#         if filename.endswith(".xml"):
#             tree = ET.parse(folder +filename)
#             root = tree.getroot()
#             try:
#                 if is_censorship(root[-1].text):
#                     files[filename] = []
#                     files[filename].append(root[-1].text)
#                     files[filename].append(root[3].text)
#                     files[filename].append(root[4].text)
#                 # add it to corpus; '-1' signifies the last element in the .xml file, which is <FullText>
#             except IndexError:
#                 continue
#             i += 1 # for this version we only run 10000 iterations and break after th
#         if i == 10004:
#             break
#     if i == 10004:
#         break    

In [ ]:
# i = 0 # Here we selectively add folders to our corpus
# folders = ["NYT/sm_55428_1004/","NYT/sm_55428_1005/"]
# for folder in folders:
#     for filename in os.listdir(folder):
#         if filename.endswith(".txt"):
#             files[filename] = []
#             try:
#                 if is_censorship(filename):
#                     file = open(filename, "r") 
#                     files[filename].append(file.read())
#                 # add it to corpus; '-1' signifies the last element in the .xml file, which is <FullText>
#             except IndexError:
#                 continue
#     i += 1 # for this version we only run 10000 iterations and break after th
#     if i == 10004:
#         break

In [11]:
# os.listdir("NYT/sm_55428_1004/") # to view lists

In [12]:
for file in files: # Here we can see the list of articles that are related to censorship and will be topic modeled
    print(file + "\t" + files[file][1] + "\t" + files[file][2])

sm_55428_1004-11246.xml	Apr 14, 1859	18590414
sm_55428_1004-12061.xml	Sep 10, 1860	18600910
sm_55428_1004-12501.xml	Details of Events which Preceded the Bombardment.	Apr 16, 1861
sm_55428_1004-12638.xml	Mar 13, 1860	18600313
sm_55428_1004-12769.xml	The News' Bill--Its Effect on the Character of the House of Commons The Bill to Secure the Independence of Parliament--The Cherbourg Feter--The Case of Lady Bulwer--Aristocratic Delinquencies--Harvest--Crops--Miscellaneous.	Aug 6, 1858
sm_55428_1004-13586.xml	Jul 17, 1860	18600717
sm_55428_1004-13622.xml	Aug 26, 1861	18610826
sm_55428_1004-13949.xml	Mar 6, 1860	18600306
sm_55428_1004-13977.xml	IMPORTANT CONGRESSIONAL PROCEEDINGS. A Vote in the House to Sustain Major Anderson and the President. Another Blood and Thunder Speech by Senator Toombs. Dismal Reports of the Condition of Affairs in Charleston. Correspondence between the South Carolina Commissioners and the President. The State Conventions in Alabama and Mississippi.Messages of the Go

sm_55428_1005-37529.xml	Almost a Call at Mayor Wood's House The Princes Visit the Astor Library Reception of the Echnological Society and Families of the Common Council Presents forthe Tycoon, &c.	Jun 28, 1860
sm_55428_1005-38134.xml	Prompt Answers to the Call for Volunteers. List of States and the Number of Regiments.The State of Feeling in Washington.PROTRACTED SESSION OF THE CABINET.FORT PICKENS SOON TO BE ATTACKED. Major Anderson's Farewell to Fort Sumter.Several of his Men Killed and Wounded by a Cannon Explosion.The Baltic to Bring the Garrisonto New-York. PROTRACTED CABINET SESSION. WASHINGTON NOT UNDER MARTIAL LAW. ANTICIPATED ATTACK ON FORT PICKENS. COL. LANDER AND THE DISTRICT VOLUNTEERS. TENDER OF VOLUNTEERS FROM BALTIMORE. THE TIMES CORRESPONDENT AT WASHINGTON. THE NEW-YORK APPOINTMENTS. MOVEMENTS OF THE DIPLOMATIC CORPS. WASHINGTON APPOINTMENTS. BALTIMORE APPOINTMENTS. DISPATCH TO THE ASSOCIATED PRESS.	Apr 16, 1861
sm_55428_1005-39684.xml	May 31, 1859	18590531
sm_55428_100

sm_55428_1006-35957.xml	IMPORTANT CONGRESSIONAL PROCEEDINGS. A Vote in the House to Sustain Major Anderson and the President. Another Blood and Thunder Speech by Senator Toombs. Dismal Reports of the Condition of Affairs in Charleston. Correspondence between the South Carolina Commissioners and the President. The State Conventions in Alabama and Mississippi.Messages of the Governors of Virginia,Ohio and Illinois.The Movement of Troops from Governor's Island.OUR WASHINGTON DISPATCHES.	Jan 8, 1861
sm_55428_1006-36698.xml	May 3, 1863	18630503
sm_55428_1006-36753.xml	Jul 20, 1862	18620720
sm_55428_1006-37120.xml	Aug 30, 1859	18590830
sm_55428_1006-37159.xml	Sep 23, 1864	18640923
sm_55428_1006-37820.xml	Politics at the Capital--The Anglo-French Intervention--Anticipated Advance of Miramon upon Vera Cruz--Gen. Lerdo de Tejada in the Cabinet of Juarez--Cruelities of Miramon.	Feb 22, 1859
sm_55428_1006-37910.xml	Mar 30, 1862	18620330
sm_55428_1006-38873.xml	Additional and Interesting Details. 

sm_55428_1008-1656.xml	EXPECTED ATTACK ON THE TEXAS COAST. GEORGIA AND SOUTH CAROLINA. APPEAL FOR THE DEFENCE OF CHARLESTON. MISCELLANEOUS. MITIGATING THE HORRORS.	Jan 31, 1865
sm_55428_1008-16694.xml	How the Retreat of Gen. Banks is Received Sensations, Rumors, Theories,Queries, &c.	May 27, 1862
sm_55428_1008-17496.xml	SENATE. ASSEMBLY. A Letter from George Sanders. From San Francisco.	Jan 8, 1863
sm_55428_1008-18355.xml	Aug 29, 1866	18660829
sm_55428_1008-18959.xml	Recent Military Events--Rumored Capture of Richmond--The Censorship--Observance of the Fourth--Fires--Vote on the New Constitution--Miscellaneous Items.	Jul 10, 1862
sm_55428_1008-1953.xml	The Plans of Gen. McClellan--The Fifth New-York Zouaves--The Sounds of Battle--Military Discipline--From Baltimore to Yorktown--Camp Hamilton Big Bethel.	Apr 26, 1862
sm_55428_1008-2044.xml	B RD OF SUPERVISORS. Operations of the Excise Commissioners --Interesting Letter from Archbishop Hughes--Revolution in the new Courts House Managemen

sm_55428_1009-21619.xml	Affairs and Incidents Preceding the Surrender. Movements of the Division of Gen. W.S. Smith--The Works at Snyder's Bluff--A Ride Around Vicksburgh--Incidents of the Slege--Arrival of the Ninth Corps, &c. Correspondence of the New-York Times. THE REGION ROUND VICKSBURGH. A RIDE TO VICKSBURGH. VARIOUS EXCITING ADVENTURES. BRISK FIRING AND COUNTER FIRING. A GLIMPSE INSIDE OF VICKSBURGH.	Jul 9, 1863
sm_55428_1009-22218.xml	Paris Gossip--A New Play by Emile Augier--The claque of French Theatres--What it is and how it is Managed--A Parliamentarian Playwright--His Drama has a Run of One Night--Idieness in Paris--Rich men, Gamblers and Chevaliers d'Industrie--Nine Hundred Tales for Sixty Dollars--Gustave Doro to Hustrate Shakespeare. The Withdrawal of French Troops from Mexico--How the Official Announcement is Received in Paris--Trouble in Mexican Stocks--The Army of the Rhine--European Complications.	Apr 22, 1866
sm_55428_1009-22546.xml	The Suspension of Gen. Blenker f

sm_55428_1010-38212.xml	OUR MUTUAL FRIEND. BY CHARLES DICKENS. With Illustrations, in two parts, 8vo. New-York: HARPER & BROTHERS. PLAIN TALK ON FAMILIAR SUBJECTS. By TIMOTHY TITCOMB, (Dr. J.G. HOLLAND.) 12mo. NewYork: CHARLES SCRIBNER & Co. WALT. WHITMAN'S DRUM TAPS. l2mo. NewYork, 1865. SONGS OF PRAISE, AND POEMS OF DEVOTION OF THE CHRISTIAN CENTURIES. With Introduction, By HENRY COPPEE, Professor of EnglishLiterature in the University of Pennsylvania. Royal8vo. Philadelphia: E.H. BUTLER & Co. THE POETICAL WORKS OF WINTHROP MACKWORTH PRAED. With a Memoir, By Rev. DERWENT COLERIDGE, 2 vols., 24mo.; "blue and gold"edition. New-York: W.J. MIDDLETON. ON THE CAM.--LECTURES ON THE UNIVERSITY OF CAMBRIDGE, IN ENGLAND, By WILLIAM EVERETT, A.M. Cambridge, Mass.; SIVER & FRANCIS. THE HUMBUGS OF THE WORLD: an Account of Humbugs, Delusions, Impositions, Quackeries, Decents and Deceivers Generally, of all Ages. By P.T.BARNUM, 12mo, New-York: G.W. CARLETON.	Nov 22, 1865
sm_55428_1010-38433.xml	Feb

sm_55428_1012-17507.xml	Moral Aspect of the City--Baron Haussmann's Improvement Upon it--Regulation of Literature--Foreign Taste in the matter of books and and Plays.	May 9, 1868
sm_55428_1012-17784.xml	The Match Day of the American Jockey Club at Jerome Park--Four Interesting Matches Run--The Leamington Filly Wins the Ten-Thousand-Dollar Match--Glenelg, Intrigue and Passaic the Others. The Union Course, Long Island, Trofting Meeting--Second Day--American Girl Wins the Twenty-five Hundred Dollar Purse.	Jun 3, 1869
sm_55428_1012-17815.xml	Aug 11, 1867	18670811
sm_55428_1012-18989.xml	Humors and Amenities of the English Elections What the Papers Say About Farragal and the Sublime Porte. French Comments on the Chinese Mission. Story of an Appalling Tragedy at Sea. AFFAIRS IN ENGLAND The Elections--Pleasantries of English Politics--The Church and State Question -- Ritualistic Celebration -- Mrs. Roebuck's Outbreak at Sheffield. PROGRESS OF RITUALISM. DISRAELI AND GLADSTONE. MR. ROEBUCK'S D

sm_55428_1014-20257.xml	Rapid Advance of the Prussian Armies on Paris Determination of the French to Continue the Struggle to the End "France Yields Not One Foot of Soil; Not a Stone of a Fortress." The Plan of the Prussian Advance Report that the Garrison at Metz PARIS Support for the Republic Expected from this Country--The Prussian Advance on the Capital--Plan of the Attack--The Crown Jewels Unity of the People--Satisfaction With the Freedom of the Press-Gathering of Troops--Paris Fully Prepared for the Struggle Soldiers' Camps in the City -- Crowds About the Strasbourg Statue -- The Prussians to be "Severe with Paris." Declaration of Juies Favre--France will not Yield "One Foot of Soil; not a Stone of a Fortress." THE KING AND THE EMPEROR A Singular Report in a Paris Paper--The King Brutal and Anxious to have the Emperor Shot THE ADVANCE ON PARIS Rapid Progress of the Prussians--Heads of the Advancing Column Halting at Laon and Epernay THE SURRENDER AT SEDAN	Sep 8, 1870
sm_55428_10

sm_55428_1015-42894.xml	Interesting Narrative of Commissioner Davenport's Work. How the Records Were Arranged---The Census Tables Brought Into Requisition--- An Efficient Reply to Libelers.	Oct 31, 1872
sm_55428_1015-43732.xml	Nov 20, 1872	18721120
sm_55428_1015-44083.xml	SECOND SESSION. HOUSE OF REPRESENTATIVES.	Jan 28, 1872
sm_55428_1015-44191.xml	Nov 22, 1872	18721122
sm_55428_1015-45043.xml	Sep 4, 1872	18720904
sm_55428_1015-45525.xml	THE DIFFICULTY EXPERIENCED IN ENFORCING THE AUTHORITY OF THE HOME GOVERNMENT.	Dec 5, 1873
sm_55428_1015-45671.xml	THE RECENT EXECUTIONS AT SANTIAGO DE CUBA.NOTHING TO SHOW THAT ANY PRISONERS WERE SHOT AFTER THE 8TH INST. THE QUESTION OF AGE THE PRETENDED CONVERSIONS.	Nov 26, 1873
sm_55428_1015-46617.xml	Jun 15, 1871	18710615
sm_55428_1015-47137.xml	THE METEROPOLITAN THEATRES NEW BOOKS.	Dec 14, 1873
sm_55428_1015-47175.xml	The Territorial Election on Monday, 7th inst.--How the Mormons Voted.	Aug 16, 1871
sm_55428_1015-47744.xml	THE FENIANS. EUROPE CONG

sm_55428_1017-37543.xml	The Anniversary Gatherings of the Hicksites and the Orthodox Friends The Quaker Meeting Silent and Spoken Eloquence Progression in Their Faith.	May 19, 1872
sm_55428_1017-38268.xml	Nov 8, 1871	18711108
sm_55428_1017-38835.xml	REPORT OF THE ORGANIZATION FOR THE PAST YEAR. A VALUABLE AUXILIARY TO THE ADMINISTRATION OF CHARITY THE RELIEF SYSTEM INVESTIGATED IMPORTANT FACTS AND FIGURES HOW CHARITY IS MISAPPLIED SUGGESTIONS FOR REMEDYINGTHE EVIL.	Nov 7, 1874
sm_55428_1017-39345.xml	AN IMPORTANT MEETING YESTERDAY.REPORT REGARDING THE SLAUGHTER-HOUSE BUSINESS IN THE CITY QUACK DOCTORSTO BE PROSECUTED THE WORK OF THE SANITARY BUREAU. VITAL STATISTICS.	Sep 3, 1874
sm_55428_1017-40043.xml	Interesting Narrative of Commissioner Davenport's Work. How the Records Were Arranged---The Census Tables Brought Into Requisition--- An Efficient Reply to Libelers.	Oct 31, 1872
sm_55428_1017-4012.xml	The Tichborne Case American Works at the Royal Academy Browning's New Poem.	May 19, 18

sm_55428_1019-25381.xml	SENATOR FRELING HUYSEN AND THE SO-CALLED "GAG-LAW." THE ATTACKS UPON THE LAW REVIEWED THE NEW-JERSEY SENATOR'S CONNECTION WITH ITS PASSAGE EXPLAINED THE LAW ANALYZED.	Sep 29, 1874
sm_55428_1019-25679.xml	THE RESOLUTION OF CENSURE ON HIM, PASSED BY THE HOUSE OF REPRESENTATIVES IN 1862, RESCINDED YESTERDAY --THE SENATOR MUCH PLEASED--BETTER LATE THAN NEVER.	Mar 3, 1875
sm_55428_1019-25780.xml	PILGRIMS TO PARAY-LE-MONIAL. FOREIGN AFFAIRS FROM AN ENGLISH POINT OF VIEW THE THEATRES AND OPERA EXTRA POLITENESS AND CHARLES MATHEWS. ITALIAN UNITY. RELIGION AND POLITICS THE "LAST OF THE STUARTS." THEATRICAL GOSSIP. ENGLISH MORALITY. ANOTHER DRAMA. OPERA AT DRURY LANE. PROMENADE CONCERTS. A REWARD FOR POLITENESS.	Sep 6, 1873
sm_55428_1019-27247.xml	What the Independent Press Thinks of the Senator's Explanation A Cold Bath for an Ardent "Reformer" Parting Words to a Politician Retiring from Business.From the Chicago Evening Post.	Sep 7, 1872
sm_55428_1019-28327.xml	Aug 4, 1

sm_55428_1021-21496.xml	THE EASTERN QUESTION REVIEWED. WILL THERE BE PEACE OR A PROLONGATION OF THE WAR THE INDEPENDENCE OF BULGARIA DEMANDED GERMANY'S AID THE SPREAD OF NIHILISM.	Nov 3, 1877
sm_55428_1021-22560.xml	Dec 18, 1876	18761218
sm_55428_1021-22804.xml	Dec 21, 1873	18731221
sm_55428_1021-23250.xml	Oct 12, 1877	18771012
sm_55428_1021-23281.xml	MUSIC AND THE DRAMA IN THE METROPOLIS. THE HEALTH OF THE QUEEN--CONCERTS OF THE SEASON--THE PREVALENCE OF OPERA BOUFFE--THE CENSORSHIP-- SHAKESPEARE AT THE LYCEUM. MUSIC OF THE SEASON. THE METROPOLITAN THEATRES. THE CENSORSHIP IN ENGLAND AND AMERICA. SHAKESPEAREAN REPRESENTATIONS.	Nov 29, 1874
sm_55428_1021-24749.xml	A FIELD DAY FOR THE TAMMANY BOARD. THE REPUBLICAN PARTY CENSURED FOR THE ACT OF THE MAYOR AND HIS COLLEAGUES IN REDUCING LABORERS' WAGES--ANIMATED DEBATE REGARDING THE POLITICAL ALLUSIONS--RESOLUTION DENOUNCING THE DEMOCRATICPARTY DEFEATED--ADOPTION OF AREPORT AGAINST THE MANAGEMENT OFTHE FINANCE DEPARTMENT.	Jun 4, 1875
sm_55

sm_55428_1023-10078.xml	EXECUTIVE VIEWS AND MEASURES. THE SOUTHERN POLICY--HAPPY RESULTS OF REMOVING THE TROOPS--APPEAL TO THE MERCY OF THE EX-SLAVEHOLDERS FOR THE FREEDMEN--THE POLICY OF RESUMPTION TO BE STEADILY PURSUED--PAYMENT OF THE DEBT IN DEPRECIATECOIN REPUDIATION--CIVIL SERVICE REFORM--SOLICITUDE OVER THE MEXICANBORDER--TEA AND COFFEE DUTIES RECOMMENDED. WITHDRAWAL OF THE ARMY FROM THE SOUTH. THE EX-SLAVEHOLDERS AND NEW CITIZENS. THE CURRENCY--SPECIE PAYMENTS. THE SILVER DOLLAR AND LEGAL TENDER. SILVER IN EVERY-DAY TRANSACTIONS. THE CIVIL SERVICE. THE CIVIL SERVICE COMMISSION. FOREIGN RELATIONS. THE MEXICAN BORDER. THE CUBAN REVOLT. THE VENEZUELA CLAIMS. CENTRAL AND SOUTH AMERICA. THE SAMOAN ISLANDS. TRADE WITH FOREIGN COUNTRIES. THE REVENUE AND EXPENDITURES. CUSTOM-HOUSE REFORM. THE PUBLIC CREDIT. SHIPPING TRADE. THE INDIAN WAR. THE LABOR RIOTS. THE MEXICAN RAIDS. THE ARMY. THE NAVY. THE POST OFFICE DEPARTMENT. THE JUDICIAL DEPARTMENT. THE INDIANS. DEPREDATIONS ON TIMBER LAND

sm_55428_1025-11287.xml	HE DENOUNCES PLAY-HOUSES AND EXHORTS PLAYERS TO GIVE UP THEIR PROFESSION AND PREACH THE GOSPEL.	Jan 15, 1877
sm_55428_1025-12566.xml	NEW-YORK AND OSWEGO MIDLAND. A PLAN SUBMITTED FOR THE REORGANIZATION OF THE ROAD--DETAILS OF THE SCHEME--OBLIGATIONS OF BONDHOLDERS--THE LIMIT OF TIME.	Nov 17, 1878
sm_55428_1025-13783.xml	Dec 7, 1881	18811207
sm_55428_1025-14136.xml	Feb 8, 1880	18800208
sm_55428_1025-14283.xml	CHAPTER I. MOIRA SEEKS THE MINISTER. CHAPTER II. A VISIT TO GREAT PEOPLE. CHAPTER III. A MEETING OF LOVERS.	Mar 28, 1875
sm_55428_1025-14747.xml	THE TRIAL OF REV. C.P. M'CARTHY. EXTRAORDINARY PROCEEDINGS IN THE THIRD UNIVERSALIST CHURCH M. M'CARTHY ANNOUNCES THAT HE HAS NO RESPECT FOR CERTAIN MEMBERS OF THE COMMITTEE HE DENOUNCES THEIR ACTION AND THAT OF HIS PROSECUTOR SEVERELY.	May 24, 1877
sm_55428_1025-14920.xml	May 13, 1877	18770513
sm_55428_1025-15487.xml	Oct 1, 1879	18791001
sm_55428_1025-15540.xml	Jun 5, 1878	18780605
sm_55428_1025-17018.xml	Feb 17, 1

sm_55428_1027-46403.xml	ENGLISH LITERATURE IN 1878. AN ERA UNPRODUCTIVE OF GOOD WORK GOSSIP OF THE DAY IN LONDON PLAYWRIGHTS AND PLAYERS HENRY IRVINGAND ALFRED TENNYSON. AS THE OLD YEAR DEPARTS. IN THE FUTURE. ART AND LITERATURE.	Jan 12, 1879
sm_55428_1027-47216.xml	Jun 27, 1880	18800627
sm_55428_1027-47867.xml	CLOSING THE THEATRES. FOREIGN MUSICAL NOTES.	Jun 30, 1879
sm_55428_1027-48865.xml	Dec 9, 1877	18771209
sm_55428_1027-49805.xml	HOLDING A VISITATION IN THE CENTRAL PRESBYTERIAN CHURCH.	Mar 12, 1880
sm_55428_1027-5918.xml	MILITARY RULE IN RUSSIA. MARTIAL LAW BUT NOT A REIGN OF TERROR HOW EXAGGERATED REPORTS GET ABROAD.	May 30, 1879
sm_55428_1027-6215.xml	HORACE H. DAY.	Aug 27, 1878
sm_55428_1027-6346.xml	MUSICAL AND DRAMATIC. THE ORATORIO SOCIETY. CHAMBER MUSIC. UNION-SQUARE THEATRE. MUSICAL NOTES.	Apr 18, 1879
sm_55428_1027-6379.xml	FIRST-STREET AGITATORS GATHERING.THE COMMUNISTS' PROTEST--WHAT THEY ARE GOING TO DO IN GERMANY--ORGANIZING THE GERMAN ELECTION FUND--AN APPEAL TO PUB

sm_55428_1030-4678.xml	THE ANNUAL EXAMINATION AT WEST POINT. THE FIRST CLASS PREPARING FOR GRADUATION--A SKIRMISH DRILL BEFORE THE BOARD OF VISITORS--QUESTIONS FOR THE INVESTIGATORS TO SOLVE.	Jun 6, 1882
sm_55428_1030-47776.xml	Nov 15, 1881	18811115
sm_55428_1030-48372.xml	GEN. WOODFORD DECLARES HE NEVER SLANDERED OR CRITICISED THE PRESIDENT.	Dec 31, 1882
sm_55428_1030-49779.xml	FATHER O'FARRELL'S GIFT TO THE CATHOLIC CHAPEL OF ST. THERESA.	Jun 26, 1882
sm_55428_1030-519.xml	THE RAILWAY WAR STILL FIERCELY WAGED. THE ST. PAUL POOL BROKEN. THE NORTH-WESTERN POOL. A WAR BETWEEN THE RIVAL RAILROAD COMPANIES--THE CAUSES OF IT. DIFFERENTIAL RATES. THE QUESTION DISCUSSED BY THE RAILROAD MEN YESTERDAY. ERIE'S ROUTE TO THE WEST. GENERAL RAILWAY NEWS.	Nov 26, 1882
sm_55428_1030-5604.xml	THE FRENCH HOSTILITIES AGAINST TONQUIN.	Aug 4, 1883
sm_55428_1030-6284.xml	Aug 29, 1882	18820829
sm_55428_1030-6518.xml	MRS. HOLBROOK'S CLAIM AGAINST HER HUSBAND'S ESTATE NOT ALLOWED.	Jul 8, 1879
sm_55428_1030-73

sm_55428_1034-23345.xml	Oct 7, 1883	18831007
sm_55428_1034-24687.xml	Mar 10, 1882	18820310
sm_55428_1034-24945.xml	Sep 23, 1882	18820923
sm_55428_1034-26177.xml	Jan 3, 1883	18830103
sm_55428_1034-32106.xml	Feb 17, 1884	18840217
sm_55428_1034-32371.xml	Apr 26, 1880	18800426
sm_55428_1034-33586.xml	TWO CANDIDATES QUARRELING OVER A VACANT CAPTAINCY.	Apr 3, 1883
sm_55428_1034-35252.xml	ASSEMBLYMEN WHOSE VIRTUE CRIED FOR VINDICATION. AN OUTPOURING OF BILE AND A VOTE OF CENSURE--A STOLEN BILL--THREE HEADS FOR THE PARK DEPARTMENT.	May 16, 1884
sm_55428_1034-35324.xml	Mar 17, 1884	18840317
sm_55428_1034-36273.xml	Dec 7, 1881	18811207
sm_55428_1034-36625.xml	THE DAY AT GLEN ISLAND, ROCKAWAY, AND CONEY ISLAND.	Jul 30, 1883
sm_55428_1034-3708.xml	Feb 28, 1880	18800228
sm_55428_1034-37110.xml	THE EARLY ACHIEVEMENTS OF THE HUNGARIAN PATRIOT. HIS EFFORTS TO MAKE HIS COUNTRY FREE --ENGLAND AND AMERICA VISITED-- THE HARDSHIPS OF AN EXILE.	Dec 18, 1884
sm_55428_1034-39723.xml	ASSEMBLYMEN WHOSE VIRTUE C

sm_55428_1038-13438.xml	HE TAKES THE OATH AT TIRNOVA IN THE PRESENCE OF THE GREAT SOBRANJE--MUCH ENTHUSIASM.	Aug 15, 1887
sm_55428_1038-14073.xml	AMENDMENT TO THE LAW TO BE PREPARED.	Nov 11, 1887
sm_55428_1038-16912.xml	Jun 4, 1888	18880604
sm_55428_1038-25671.xml	Oct 17, 1886	18861017
sm_55428_1038-26366.xml	Nov 16, 1887	18871116
sm_55428_1038-26428.xml	THIRTEEN FIRMS SIGN THE AMALGAMATED SCALE. BUT ALL THE MILLS AND THE EMPLOYES ARE IDLE--CARNEGIE & CO. AMONG THOSE WHO HAVE SIGNED.	Jul 3, 1888
sm_55428_1038-30437.xml	Feb 6, 1885	18850206
sm_55428_1038-32588.xml	WILSON BEFORE THE GRAND JURY BUT NO INDICTMENT YET FOUND.	Dec 4, 1885
sm_55428_1038-33047.xml	GRAVE FEARS FOR THE SAFETY OF THE BRITISH COLUMN. THE BATTLE OF ABU-KLEA NOT A DECISIVE BRITISH VICTORY--GEN. STEWART INTRENCHED--NEWS SUPPRESSED.	Jan 24, 1885
sm_55428_1038-33804.xml	May 15, 1887	18870515
sm_55428_1038-34199.xml	CLOSING SCENES IN THE LEGISLATIVE HALLS.A HEAVY BATCH OF NOMINATIONS CONFIRMED BY THE SENATE--THE EXECUTIV

sm_55428_1042-9209.xml	Nov 6, 1889	18891106
sm_55428_1043-10386.xml	JOE HOWARD ENTERTAINS A BOSTON AUDIENCE.	Dec 6, 1886
sm_55428_1043-10479.xml	HE MAKES MANY CHANGES IN CITY OFFICES. MEN UNKNOWN IN PUBLIC LIFE APPOINTED TO RESPONSIBLE PLACES--POLITICIANS DISPLEASED. THERE'S A ROW IN TAMMANY.	May 3, 1889
sm_55428_1043-12059.xml	THE PITIFUL STORY TOLD BY FELIX VOLKHOVSKY. SEVEN YEARS OF SOLITARY CONFINEMENT ENDS IN EXILE TO SIBERIA -- THE VICTIM A NERVOUS WRECK.	Nov 23, 1890
sm_55428_1043-12293.xml	ONE IN CHICAGO AND THE OTHER IN ST. PAUL.	Jan 20, 1887
sm_55428_1043-12944.xml	Jun 15, 1888	18880615
sm_55428_1043-14322.xml	Jan 23, 1887	18870123
sm_55428_1043-14628.xml	Apr 14, 1888	18880414
sm_55428_1043-17878.xml	EFFECTS THAT WOULD FOLLOW THE TURN IT TOOK. FOR THE RETURN OF THE PRINCES-- PANAMA SHAREHOLDERS BEAUTIFULLY CONFIDENT--CARDINAL LAVIGERIE'S AMBITION--MILAN'S POSSIBLE ABDICATION.	Dec 30, 1888
sm_55428_1043-17904.xml	Feb 15, 1889	18890215
sm_55428_1043-18046.xml	Apr 22, 1887	18870

sm_55428_1045-9100.xml	LES PLAISIRS EN CHINE. Par le General TCHENG-KI-TONG, Paris: G. CHARPENTIER ET CIE.	Sep 7, 1890
sm_55428_1045-9160.xml	Mar 26, 1887	18870326
sm_55428_1045-9589.xml	Jan 2, 1889	18890102
sm_55428_1045-9780.xml	THAT OF KANSAS AND OF NEW-YORK COMPARED. AND THE COMPARISON IS NOT FAVORABLE TO NEW-YORK -- MORE GOOD SPEAKERS IN KANSAS THAN HERE.	May 25, 1890
sm_55428_1046-11951.xml	TALK OF A REPUBLIC COMING TO THE SURFACE. TRADE RETALIATION -- TALBOT'S DEATH AND LORD NAPIER'S FUNERAL - READING'S AFFAIRS.	Jan 19, 1890
sm_55428_1046-12254.xml	INSIDE HISTORY CONCERNING THE CZAR ALEXANDER III. A BORN "POTTERER," WITH NO IDEA OF SYSTEM AND NO EXECUTIVE TALENT -- HIS COMICAL OBJECTION TO WAR -- RUSSIAN IGNORANCE OF THEIR OWN RULER.	Nov 2, 1891
sm_55428_1046-12808.xml	THAT OF KANSAS AND OF NEW-YORK COMPARED. AND THE COMPARISON IS NOT FAVORABLE TO NEW-YORK -- MORE GOOD SPEAKERS IN KANSAS THAN HERE.	May 25, 1890
sm_55428_1046-14471.xml	FEATURES OF FIVE CHAPTERS HE HAS ALREADY WRI

sm_55428_1048-25576.xml	Dec 12, 1890	18901212
sm_55428_1048-27061.xml	ESTABLISHMENT OF STRICT QUARANTINE REGULATIONS DEMANDED.	Sep 17, 1892
sm_55428_1048-27669.xml	ARGUMENTS ON THE LAW'S SECTION WHICH AFFECTS NEWSPAPERS. THE CASES OF TWO JOURNALS BEFORE THE UNITED STATES SUPREME COURT -- CLAIMS THAT CONGRESS HAS EXCEEDED ITS POWERS.	Nov 17, 1891
sm_55428_1048-28259.xml	Dec 26, 1889	18891226
sm_55428_1048-29096.xml	PRINCETON '92 PLANTS ITS IVY AND HAS ITS "CANNON" EXERCISES.	Jun 14, 1892
sm_55428_1048-2984.xml	THE CIVIL SERVICE COMMISSION COURTS PUBLICITY. ENCOUNTERS WITH SENATORS PLUMB AND GORMAN IN WHICH THOSE STATESMEN USED "DIGNIFIED SILENCE" OF THE QUAY VARIETY.	Jul 3, 1891
sm_55428_1048-29860.xml	OSCAR WILDE REPUDIATES ENGLAND FOR FRANCE.	Jul 18, 1892
sm_55428_1048-31980.xml	FLOUR MILLS CLOSED ON ACCOUNT OF THE CRUCIFIXION. IDIOCIES OF RUSSIAN GOVERNORS -- JEWS DRIVEN OUT WHO STOOD BETWEEN THE PEASANTS AND FAMINE -- THE ST. PETERSBURG EXPULSIONS.	Nov 16, 1891
sm_55428_1048-32559.x

sm_55428_1049-9664.xml	Jun 25, 1892	18920625
sm_55428_1049-9820.xml	NANSEN'S CROSSING OF GREENLAND. THE FIRST CROSSING OF GREENLAND. By FRIDNOV NANSEN. Translated from the Norwegian by HUBERT MAJENDIE GEPP, B. A., Lecturer at the University of Upsala. With maps and numerous illustrations. In two volumes London and New-York: LONGMANS, GREEN & CO. 1890.	Dec 28, 1890
sm_55428_1050-10913.xml	Jun 15, 1892	18920615
sm_55428_1050-10944.xml	SOMETHING ABOUT "THE WEAVERS," NOW EXCITING BERLIN.	Mar 19, 1893
sm_55428_1050-11094.xml	Aug 20, 1893	18930820
sm_55428_1050-11287.xml	SWEETMEATS, CIGARS, AND WINES TO BE SENT FROM NEW-YORK. A "Patriotic League" Has Been Formed, and Contributions Will Be Received at the Japanese Consulate -- Japanese Residents of This City and Brooklyn Enthusiastic in Their Support of the Home Government -- Mr. Inamoto's Speech.	Aug 13, 1894
sm_55428_1050-11337.xml	THE STUDENT HAD A GALA DAY AT THE COLLEGE EXERCISES YESTERDAY.	Jun 9, 1891
sm_55428_1050-12030.xml	Oct 5, 1893

sm_55428_1051-12377.xml	PUSHING HER TROOPS ON TO THE NEIGHBORHOOD OF PEKIN. A Great Battle in Which the Chinese Were Defeated -- Treaty-one Transports Sail from Japan, Their Destination a Secret -- China Concentrating Her Forces for Defensive Operations -- Li Hung Chang Blamed for Her Reverses.	Sep 17, 1894
sm_55428_1051-1250.xml	FLOUR MILLS CLOSED ON ACCOUNT OF THE CRUCIFIXION. IDIOCIES OF RUSSIAN GOVERNORS -- JEWS DRIVEN OUT WHO STOOD BETWEEN THE PEASANTS AND FAMINE -- THE ST. PETERSBURG EXPULSIONS.	Nov 16, 1891
sm_55428_1051-1375.xml	CHRISTIAN ENDEAVOR SOCIETIES MEET IN CONVENTION. MANY THOUSANDS OF DELEGATES FILL THE CITY. MADISON SQUARE GARDEN TOO SMALL TO HOLD MORE THAN ONE-HALF THE THRONG -- AN ORGANIZATION WHOSE GROWTH HAS BEEN PHE- NOMENAL -- OVER 1,000,000 MEM- BERS IN ELEVEN YEARS JOIN 22,000 SOCIETIES -- EARNEST AD- DRESSES TO EARNEST MEN AND WOMEN -- THE CONVENTION ORGAN- IZED AND AT WORK.	Jul 8, 1892
sm_55428_1051-13891.xml	MEMBERS OF THE CITY CLUB HEAR PROMINENT SPEAKERS

sm_55428_1052-26879.xml	SUGGESTS NEW PLOTS OF RUSSIA AGAINST STURDY BULGARIA. The Telegram He Received Before He Made His Speech -- Consternation of the Regents at the Banquet -- Sketch of the Young King's Person and Character -- Servia's Army Eager to Wipe Out the Slivnitza Defeat -- The Religious Question Envenoms the Situation -- Proclamation of a Republic in Belgium Expected -- Feeble Concessions to the Popular Discontent -- That French, Fleet at Alexandria -- Darkness Shrouds the Egyptian Question -- Tories in Parlia- ment Stave Off a Vote on Homo Rule- Pierce Mahony Puts Bailiffs in Davitt's Cottage -- Tory Violence in Parliament Condoned by the Speaker -- London's Lord Mayor Toasts the Pope and the Queen.	Apr 16, 1893
sm_55428_1052-27000.xml	Jul 20, 1894	18940720
sm_55428_1052-27921.xml	The Board of Control Chooses Mr. August Belmont a Member.	Sep 20, 1893
sm_55428_1052-28358.xml	Dec 23, 1894	18941223
sm_55428_1052-2914.xml	NATURAL HISTORY OF INTELLECT, AND OTHER PAPERS. By Ralp

sm_55428_1053-35845.xml	BUILDING A PONTON BRIDGE UN- DER A BROILING SUN. The Senior Class Examined in the Techni- calities of Law -- Their Proficiency As- tonishes the Most Learned Lawyers -- Superintendent Ernst Explains the Needs of the Military Academy to the Board of Visitors -- An Increase in the Number of Cadets to Be Recommended.	Jun 6, 1893
sm_55428_1053-3637.xml	Many of His "Impressions" of the University Are Ridiculous. DESCRIPTION OF STUDENTS ABSURD A Protest Raised Against a Story in a College Paper-New Literary Society Formed -- Elections Held.	Nov 26, 1894
sm_55428_1053-36474.xml	REPUBLICANS WILL BE DEFEAT- ED ON THE HAWAIIAN QUESTION. But They Are Bound to Heap Plenty of Abuse on the President While Op- portunity Offers -- Boutelle Has His Say at Last -- The Debate Will Close To-day and the Vote Will Be Taken -- The Hitt and Boutelle Resolutions Will Be Defeated.	Feb 6, 1894
sm_55428_1053-36515.xml	Dec 25, 1895	18951225
sm_55428_1053-36630.xml	Aug 20, 1893	18930820
sm_55

sm_55428_1054-38296.xml	Dr. Frank Van Fleet Appeals for Protection in a Damage Suit -- A Committee to Consider His Protest.	Sep 24, 1895
sm_55428_1054-38489.xml	Aug 26, 1893	18930826
sm_55428_1054-39151.xml	Many of His "Impressions" of the University Are Ridiculous. DESCRIPTION OF STUDENTS ABSURD A Protest Raised Against a Story in a College Paper-New Literary Society Formed -- Elections Held.	Nov 26, 1894
sm_55428_1054-393.xml	Minister Guzman Says Revolutionists Supervise Cablegrams.	May 26, 1893
sm_55428_1054-3950.xml	Reforms Which Are Demanded but Spain Will Not Concede. AN ARRAY OF FACTS AND FIGURES Onerous Customs Duties, an Improbable Debt, an Absurd "Ley de Relaciones" and Malfeasance in Office.	May 23, 1895
sm_55428_1054-40098.xml	A Great Many Lives and Millions of Dollars to Attain Success.	Dec 8, 1895
sm_55428_1054-41103.xml	Citizens Fleeing from Rio Janeiro in Fear of Another Bombardment.	Sep 22, 1893
sm_55428_1054-41900.xml	An Important Question for the Next Legislature. MO

sm_55428_1055-626.xml	PRINCETON GRADUATES CELEBRATE CLASS-DAY EXERCISES. Cratons and Poem in the First Presbyterian Church and the Time-Honored Ivy Planting at the Foot of "Old Nassau" -- Cannon Exercises, with the Presentations and the Annual Merry-Making of the Seniors -- Oratorical Contest for the Valuable Prizes of Medals and Books.	Jun 13, 1893
sm_55428_1055-659.xml	It Must Be Perfected, Mr. Giffin Says, by Punishing the Guilty.	Nov 13, 1893
sm_55428_1055-6647.xml	Oct 13, 1895	18951013
sm_55428_1055-7423.xml	MANY PERSONS FROZEN TO DEATH -- WOLVES MADE DESPERATE.	Jan 19, 1893
sm_55428_1055-8204.xml	Three Important Papers Read at the Sessions Yesterday.	Sep 4, 1896
sm_55428_1055-8727.xml	Jul 17, 1893	18930717
sm_55428_1055-9155.xml	Feb 14, 1893	18930214
sm_55428_1055-990.xml	Oct 13, 1895	18951013
sm_55428_1056-11484.xml	Liberals Making a Strong Fight Against the Caro Government.	Apr 22, 1895
sm_55428_1056-11594.xml	THE GREAT HUNGARIAN PATRIOT DEAD AT TURIN. He Was the Deseendant of 

sm_55428_1057-23005.xml	Aug 16, 1898	18980816
sm_55428_1057-23018.xml	INTELLIGENT CITIZENS IN HAVANA THINK THEY WILL WIN. What a Professional Man of This City, Just Returned from the Island, Says of the Outlook -- Spain's Force Physically Inferior and Likely to Suffer from Yellow Fever -- Cruelties. That May Call Forth Protests from All Christendom.	Apr 18, 1896
sm_55428_1057-23080.xml	Details of the Great Destruction Wrought by Gales. CRISIS MORE ACUTE IN PARIS Prince Victor's Manifesto Already Printed and in France. Russia Sincere About a Desire for Present Peace -- A Great Federation Formed Against Organized English Workingmen.	Jan 15, 1899
sm_55428_1057-24401.xml	THE KINGDOM OF GOD IS WITHIN YOU. Christianity Not a Mystic Religion, but as a New Theory of Life. Translated from the Russian of Count Leo Tolstoi by Constance Garnett. New-York: The Cassell Publishing Company.	Mar 18, 1894
sm_55428_1057-25006.xml	Jun 13, 1897	18970613
sm_55428_1057-26347.xml	The President, in Thanking Hi

sm_55428_1058-47801.xml	Unpleasant Surprises for the Tories in the Recent By-Elections Throughout England -- The Liberals Jubilant. EXPLORER NANSEN THE LION OF LONDON DRAWING ROOMS. Hicks-Beach's Jingoism May Have Far-Reaching Results -- Novel Settlement of Welsh Miners' Strike Prevented.	Feb 7, 1897
sm_55428_1058-47872.xml	Sep 11, 1895	18950911
sm_55428_1058-4896.xml	THE LATEST SPRING NOVELS Florence Warden's New Work. KITTY'S ENGAGEMENT. A Novel. By Florence Warden. New-York: D. Appleton & Co.	Mar 17, 1895
sm_55428_1058-5037.xml	Apr 25, 1897	18970425
sm_55428_1058-6258.xml	The Last Before the College Becomes a University.	Jun 9, 1896
sm_55428_1058-6864.xml	"Die Versunkene Glocke," "Vasantasena," and "John Gabriel Borkman" the Latest Interesting Features. THE PLOTS OF THE DRAMAS. Hauptmann's Play Excites Lively Criticism and Comment -- Ibsen's Drama Is Modern Misery -- Revival of a Sanskrit Classic.	Mar 28, 1897
sm_55428_1058-7005.xml	Sabanilla Garrison Surprised and De- feated and Ho

sm_55428_1060-12115.xml	Oct 10, 1896	18961010
sm_55428_1060-12275.xml	A Unique Exhibition in the Mercantile Library. AMERICAN, FRENCH AND ENGLISH WORK Praise for the New-York Times's Posters -- Mr. Peoples Pleased with, the Interest Taken in His Collection.	Feb 16, 1896
sm_55428_1060-13350.xml	Jan 11, 1897	18970111
sm_55428_1060-13363.xml	To Do So Didn't Seem " Wicked" to Her Just After Sumter Fell.	Jun 16, 1896
sm_55428_1060-15248.xml	Silver and Labor Factions Get Into a Hopeless Tangle. DIPLOMACY OF MR. BREWSTER Both Sides Believe They Own Him and His $1,000 -- The Democratic Club's Plans.	Mar 28, 1899
sm_55428_1060-15339.xml	May 5, 1897	18970505
sm_55428_1060-17390.xml	Mar 11, 1896	18960311
sm_55428_1060-17588.xml	Dr. Chamberlain Says All Men Should Be Judged Charitably.	Jan 13, 1896
sm_55428_1060-17756.xml	A Tour of the Coast from New York to Tampa Shows Nothing of Hostilities. TROOP TRAINS SIDE-TRACKED Gen. Shafter Not Popular in Tampa, Where Many Stories Are Told of His Unpleasan

sm_55428_1061-13636.xml	Jacksonville Under the Eye of Gen. Greely -- Cipher Messages from Newspaper Correspondents Stopped.	May 21, 1898
sm_55428_1061-13712.xml	Jan 1, 1898	18980101
sm_55428_1061-13913.xml	Oct 20, 1901	19011020
sm_55428_1061-1395.xml	Nov 4, 1899	18991104
sm_55428_1061-13986.xml	Mar 14, 1898	18980314
sm_55428_1061-14492.xml	Some of Our Finest Ships to Go to Europe When Peace Is Restored. NEW SOUTH PACIFIC STATION Long Cherished Project to Maintain a Squadron with Base at Valparaiso or Callao May Be Carried Out -The North Atlantic Fleet.	Aug 7, 1898
sm_55428_1061-14616.xml	Apr 9, 1898	18980409
sm_55428_1061-15377.xml	Mar 4, 1897	18970304
sm_55428_1061-15466.xml	Terrible Destitution Follows Failure of the Crops. Anglo-American Mission Extends Aid -- Pastor Says Conditions Are Worse Than in 1867, When 100,000 Died.	Dec 20, 1902
sm_55428_1061-15975.xml	Strict Censorship Prevents Publication of News of the Carlists.	Dec 5, 1898
sm_55428_1061-16851.xml	BOOKS AND THEIR MAKERS.

sm_55428_1061-6288.xml	Dec 23, 1900	19001223
sm_55428_1061-6949.xml	Mar 21, 1898	18980321
sm_55428_1061-6983.xml	CAPTURE OF A TRAIN WITHIN SIGHT OF HAVANA. Details of the Exploit of Arangueren's Men -- Spanish Officers Taken and Released -- A Cuban Hanged as a Traitor.	Jan 22, 1897
sm_55428_1061-7198.xml	One of Them Places Her at Key West -- Another Denies She Is There -- Navy Department Silent.	May 24, 1898
sm_55428_1061-7410.xml	Weyler said to be Killing All Prisoners Taken.	Dec 6, 1896
sm_55428_1061-8714.xml	Jan 12, 1897	18970112
sm_55428_1061-9039.xml	Nov 23, 1899	18991123
sm_55428_1061-9090.xml	Intense Interest in the Debate on the Army Bill MR. RHODES'S BERLIN VISIT Well Received by the Emperor and Financiers, but Badly by the Press -- The Tyranny of Officials THE DEBATE IN THE REICHSTAG CECIL RHODES IN BERLIN A CONSUL'S BAD MISTAKE THE CASE OF JACKSON	Apr 9, 1899
sm_55428_1061-9677.xml	Dec 20, 1898	18981220
sm_55428_1061-9932.xml	Apr 14, 1900	19000414
sm_55428_1061-9974.xml	Alde

sm_55428_1062-48371.xml	Freedom of the Press Restricted by Official Censors -- Garbling of Important News.	Sep 12, 1897
sm_55428_1062-48421.xml	A Tour of the Coast from New York to Tampa Shows Nothing of Hostilities. TROOP TRAINS SIDE-TRACKED Gen. Shafter Not Popular in Tampa, Where Many Stories Are Told of His Unpleasant Ways -- Port Tampa Improved.	Jul 10, 1898
sm_55428_1062-48439.xml	The Admiral Attends Services at St. Mary's Roman Catholic Church at Annapolis.	Jul 18, 1898
sm_55428_1062-48855.xml	Apr 30, 1898	18980430
sm_55428_1062-48944.xml	Nov 21, 1899	18991121
sm_55428_1062-49431.xml	Feb 26, 1900	19000226
sm_55428_1062-49670.xml	Mar 20, 1899	18990320
sm_55428_1062-49848.xml	Crosses Tugela and Tries to Break Through Lines. FIGHT LASTS TWO DAYS British Retain the Footing They Won on the Plateaus. LOSSES VERY SMALL. Boers Report the Cannonading the Fiercest Yet Experienced. Burghers Attack Gatacre in Cape Colony and Lord Methuen Is Active in the West -- May Be Part of General Advan

sm_55428_1063-40783.xml	But Only a Complete War Disaster Would Cause Its Downfall PRINCE OF WALES ACCUSED His Influence Said to Have Stifled Jameson Raid Inquiry. Growing Disgust at Extravagant Language of War Dispatches -- Russia Not Expected to Interfere in, the East Yet.	Feb 4, 1900
sm_55428_1063-41301.xml	Aug 11, 1897	18970811
sm_55428_1063-41481.xml	The Only Basis Upon Which Peace May Be Made in South Africa. REPUBLICS MUST BE REVIVED A Change of British Policy in That Direction May Be Expected. Mr. Chamberlain's Influence Said to Be Diminishing -- Scheme of Army Reform Not Regarded Seriously by the Country -- The Tien-Tsin Affair.	Mar 17, 1901
sm_55428_1063-41979.xml	He Says the Philippine Policy Is Full of Dangers. THE PRESIDENT RESPONSIBLE Invited to Speak Before the Anti-Imperialist League, He Replies, Attacking the Administration.	Mar 31, 1899
sm_55428_1063-42274.xml	Jun 24, 1900	19000624
sm_55428_1063-42368.xml	Senor Silvela Warns Sagasta in El Tiempo to Return to the Consti

sm_55428_1064-33686.xml	Assessment of Candidates for Judicial Office Not Mentioned. RICHARD CROKER CONDEMNED The Attack on the Tammany Administration Intensified -- To Go to the Legislature.	Jan 15, 1900
sm_55428_1064-3404.xml	Battleship Leaves Key West for Havana, Supported by the Whole of Admiral Sicard's Fleet. SECRETARY LONG EXPLAINS IT Says It Is a Friendly Call Merely -- Spain Notified of the Course to be Taken -- A Concession to the Demand for Action.	Jan 25, 1898
sm_55428_1064-34055.xml	Jan 2, 1899	18990102
sm_55428_1064-34274.xml	Nov 6, 1897	18971106
sm_55428_1064-34461.xml	The Rev. Dr. Silverman Condemns a Modern Class of Plays. TRAFFIC IN SACRED THINGS Presentations Which Invite Sects to Controversy and Tend to Promote Skepticism.	Dec 4, 1899
sm_55428_1064-35523.xml	Silver and Labor Factions Get Into a Hopeless Tangle. DIPLOMACY OF MR. BREWSTER Both Sides Believe They Own Him and His $1,000 -- The Democratic Club's Plans.	Mar 28, 1899
sm_55428_1064-35833.xml	Mar 12, 1899	189

sm_55428_1065-3269.xml	Great Confusion in the Government -- Dispatches from Minister Hart.	Sep 7, 1900
sm_55428_1065-33023.xml	Thackeray, Balzac, Liszt, Malibran, Guiccioli, Macaulay, the Bonapartes, Froude, and the Queen.	Oct 29, 1898
sm_55428_1065-33213.xml	Jan 25, 1901	19010125
sm_55428_1065-33418.xml	The Stern Man Who Shuts Off the News Yet Has the Friendship of Correspondents.	May 15, 1898
sm_55428_1065-34199.xml	MANY ADDRESSED THE CHARTER COMMISSION YESTERDAY. State Superintendent Skinner Wanted More Power Given to the State -- Brooklyn Educational Authorities Pleaded for Borough Rule.	Jan 12, 1897
sm_55428_1065-34414.xml	Through All His Sufferings He Is Still a French Patriot. PLEADS FOR REHABILITATION Must Live to Clear His Name for His Children's Sake -- Belief that the Real Traitor Will Yet Be Revealed.	Sep 4, 1898
sm_55428_1065-34487.xml	Dec 19, 1897	18971219
sm_55428_1065-34942.xml	Jun 23, 1900	19000623
sm_55428_1065-35340.xml	Gen. Brooke Favors Disbandment of the Insular F

sm_55428_1066-27551.xml	Production of an Opera Under Difficulties. "THE NOVICE OF PALERMO" A Manager Who Played Cards and Did Not Pay Salaries -- A Very Cheap Wedding.	Sep 16, 1900
sm_55428_1066-28213.xml	BOOKS AND THEIR MAKERS.	Mar 10, 1900
sm_55428_1066-29224.xml	Oct 24, 1899	18991024
sm_55428_1066-29385.xml	Apr 4, 1901	19010404
sm_55428_1066-29766.xml	Character of the Campaign Has Entirely Changed. BRITISH MUST NOW LAY SIEGE No Hope of Carrying Boer Positions at Colenso by Assault -- Their Up-to-Date Methods.	Dec 29, 1899
sm_55428_1066-29940.xml	Jan 27, 1901	19010127
sm_55428_1066-30352.xml	Dr. Rainsford Also Taken to Task at Methodist Preachers' Meeting -- Protest Against Invitation to Mr. Jerome.	Jan 28, 1902
sm_55428_1066-31448.xml	Two Melodramatic Plays Founded on "Quo Vadis." "Trelawny of the Wells" Revived -- A New Comic Opera -- Gossip of the Theatres.	Apr 10, 1900
sm_55428_1066-3178.xml	Eagan's Case and the Lack of Discipline in the Army. BLAME CAST UPON MR. ALGER Senator Qu

sm_55428_1067-44942.xml	States Terms on Which Aguinaldo Would Surrender. ADMITS THE WAR IS HOPELESS American Sovereignty Would be Good for the Islands, He Believes. With Proper Guarantees from the United States, He Thinks Peace Could Be Established in a Few Weeks.	May 12, 1900
sm_55428_1067-45636.xml	Feb 24, 1900	19000224
sm_55428_1067-4589.xml	The Abbe Fouard's "Last Years of St. Paul" and "Brownson's Later Life."*	Jan 5, 1901
sm_55428_1067-47073.xml	Aug 6, 1898	18980806
sm_55428_1067-47854.xml	De Wet's Dorp Garrison of Four Hundred Men Surrenders. Boers Afterward Defeated By Relief Column -- Much Alarm in Great Britain Over the General Outlook.	Nov 30, 1900
sm_55428_1067-47936.xml	How the Tenderloin Police Forego Sleep to Read a Grateful Author's "Odd tales."	Oct 5, 1900
sm_55428_1067-48017.xml	Dec 8, 1899	18991208
sm_55428_1067-4848.xml	Jul 26, 1902	19020726
sm_55428_1067-48531.xml	Observations on the Downfall of the Marquis of Dufferin and Ava. CAUGHT IN A FINANCIAL NET How the Lon

sm_55428_1069-17506.xml	An Artistic Advance Upon "The County Chairman." FRESHWATER COLLEGE COMEDY A Charming Production, and an Undistinguished Company Admirably Drilled.	Sep 21, 1904
sm_55428_1069-181.xml	No Objection to Russia's Demands Upon Turkey -- Mail Advices Tell More of Progress of Insurrection.	Aug 16, 1903
sm_55428_1069-18479.xml	Experts Publish Figures Showing That Indirect Taxation Has Become a Crushing Burden.	Nov 19, 1902
sm_55428_1069-18661.xml	Report that President Roosevelt Wants to Know Why a Cablegram to Him Was Suppressed.	May 31, 1902
sm_55428_1069-19155.xml	Says Jerome Must Wait Until Col. Mann Returns. HAS SAID HE WAS IN CHARGE But Declares Now He Hasn't the Authority to Show Accounts of "Fads and Fancies."	Jul 16, 1905
sm_55428_1069-19212.xml	Jan 20, 1899	18990120
sm_55428_1069-19648.xml	Charges Distortion of History, Cant, and False Pretense. HE CONDEMNS THE PRESIDENT Overthrow of the Administration, He Declares, Is the First Duty Un- der Present Conditions.	S

sm_55428_1070-24205.xml	Director of the Libertas Admits Having Libeled Gen. Bell -- Sentence Deferred.	Dec 2, 1902
sm_55428_1070-24495.xml	Committee in Russian City Acknowledges Receipt of Funds. Nobles Subscribe to Help Those Who Killed the Jews -- Plans for Refugees.	May 19, 1903
sm_55428_1070-24713.xml	Jun 21, 1903	19030621
sm_55428_1070-24734.xml	Dec 22, 1901	19011222
sm_55428_1070-24884.xml	Hopes for Speedy Settlement of the War Falsified. DUKE OF TECK TO BLAME? Loss of Convoy at Koernspruit Said to Have Been His Fault. Russia Is Winning Over the Bulgarians and Prince Ferdinand May Have to Go -- Cecil Rhodes's Reception an Icy One.	Apr 15, 1900
sm_55428_1070-25200.xml	Refuses to Submit Dispute to Venezuelan Courts Because Castro Will Overrule Their Decision.	Feb 13, 1901
sm_55428_1070-25825.xml	May 2, 1904	19040502
sm_55428_1070-2603.xml	What Some of Them Are Saying, Writing or Planning.	Jan 3, 1903
sm_55428_1070-26510.xml	George Eliot.*	Oct 5, 1901
sm_55428_1070-26681.xml	Mar 2, 

sm_55428_1071-38082.xml	Anarchists Planned to Wipe Out the Spanish Royal Family.	Apr 3, 1906
sm_55428_1071-38550.xml	Oscar S. Straus Urges Employers' Unions as Balancing Force. St. Clair McKelway at Boston Meeting Discusses Newspapers and Publicity.	May 15, 1903
sm_55428_1071-39304.xml	The Story of the War Among Colorado's Mines. TROOPS AND COURTS CONFLICT State Militia All Called Out -- Crime and Lawlessness Rampant -- Dynamite and Poison Used.	Jun 7, 1904
sm_55428_1071-40334.xml	Ambition of Jacob Adler to Play Before English-Speaking Audiences Arouses Difference of Opinion on the East Side -- Personal Interest in the Players -- Manager of Early Yiddish Playhouse Admires the Actor but Deplores the Attempt to Translate Shakespeare's Work.	May 31, 1903
sm_55428_1071-40530.xml	Mar 22, 1905	19050322
sm_55428_1071-42049.xml	Four Camping in Brooklyn Courts Defy Their Rivals. One Set Recognized by Justice Marean, the Other by Corporation Counsel -- Mr Dooley Arrast: Mr. Durack -- Sheriff Ref

sm_55428_1073-14895.xml	Tells Visiting Clubs the Filipinos Are Restive Under Oppression. IMMEDIATE AID PROPOSED Independence After Settlement of Tariff, Taxation, and Shipping Questions -- Perils of Imperialism. JUDGE PARKER TALKS ON PHILIPPINE ISSUE	Oct 16, 1904
sm_55428_1073-15968.xml	Absolute Censors Over the American Zone. LOTTERIES ARE PROHIBITED President Promulgates Rules and Instructions for the Commission -- Will Report to War Department.	May 10, 1904
sm_55428_1073-16098.xml	Ex-Governor of Johannesburg Charged with Inciting to Murder -- The Case Will End To-day.	Jan 18, 1902
sm_55428_1073-16416.xml	Jun 19, 1903	19030619
sm_55428_1073-16973.xml	Queer Logic of German Court Which Prohibited the Production of Heyse's "Mary of Magdala."	Feb 8, 1903
sm_55428_1073-17194.xml	Jun 26, 1905	19050626
sm_55428_1073-17807.xml	They Need to be Better Written Before They Can Compete with Fiction.	Apr 5, 1902
sm_55428_1073-18354.xml	SWEDISH FAMINE BENEFIT. Mme. Schumann-Heink and Mr. Elmblad Si

sm_55428_1074-38749.xml	Jun 22, 1901	19010622
sm_55428_1074-40220.xml	Sudermann Makes a Strong Speech Against the German Censor.	Mar 22, 1903
sm_55428_1074-41924.xml	Oct 9, 1904	19041009
sm_55428_1074-41938.xml	EFFECT OF WAR ON TRADE What Russo-Japanese Conflict Would Do to American Business -- Many Articles of Commerce Would Be Shut Off by Hostilities -- Effect on Exports.	Jan 17, 1904
sm_55428_1074-42000.xml	Supt. McCullagh Investigating 5,000 Cases of Challenges. His Deputy Alleges that Many Determined Efforts at Colonization Have Occurred This Year.	Oct 21, 1901
sm_55428_1074-42268.xml	Democrats Will Make Trip to the Philippines to Gather Facts.	Mar 12, 1901
sm_55428_1074-44812.xml	Nov 23, 1902	19021123
sm_55428_1074-45521.xml	Feb 15, 1901	19010215
sm_55428_1074-4631.xml	Dec 31, 1901	19011231
sm_55428_1074-47648.xml	Mrs. Mary Crawford Fraser's Third Letter from the Land of the Rising Sun -- How the Struggle with Russia Has Affected the Japanese Drama -- Notable Actors. THE JAPANESE

sm_55428_1076-14966.xml	But the Justice Says He Sees No Harm in What It Prints. HE WARNS THEM OF LIBEL Only When Opinion Is Asked -- Looks Out for Politics -- Skips Society Gossip on Proof Sheets.	Jul 17, 1905
sm_55428_1076-15506.xml	Ibsen's Drama of Heredity Ghosts, with a Problem Included, to be Presented at The Manhattan with Mary Shaw -- Revival of Old English Plays at Mrs. Osborn's.	Jan 25, 1903
sm_55428_1076-15652.xml	Apr 20, 1904	19040420
sm_55428_1076-15655.xml	"Un Ballo in Maschera" Awakens Enthusiasm. WORK REVAMPED BY CENSOR Old-Fashioned Opera Seen Here for First Time in Two Years -Homer and Scotti in Cast.	Feb 7, 1905
sm_55428_1076-15744.xml	Feb 2, 1907	19070202
sm_55428_1076-16809.xml	Citizens' Union Book Declares "Deveryism" Taint Is Gone. ORGANIZED BLACKMAIL ENDED Effect of Commissioner Greene Striking "Higher Up" at Delinquencies in the Uniformed Force.	Sep 27, 1903
sm_55428_1076-17590.xml	Sale of Petroleum Forbidden, Arms in Gunsmiths' Shops Hidden.	Jan 24, 1905
sm_554

sm_55428_1077-16249.xml	New York Operators Tell of Their Oriental Experienoes. ADVENTURES OF THE HAIMUN Describe Capture by Bayan and the Sinking of the Petropavlovsk After Port Arthur Bombardment.	Aug 21, 1904
sm_55428_1077-16368.xml	Dispatch Five Hours Before Oyama Entered Tells of Frightful Carnage.	Mar 11, 1905
sm_55428_1077-16565.xml	Mme. Grand on Men and Honor, Pierre Loti's Latest Book on Japan, and Max Beerbohm's Latest Book of Caricatures.	May 28, 1904
sm_55428_1077-16702.xml	He Tells How the Czar Lifted the Censorship. EXPECTS NO BALKAN WAR NOW Associated Press General Manager Also Saw German Emperor -- Other Passengers on Kaiser Wilhelm II.	Mar 9, 1904
sm_55428_1077-1733.xml	Niu-Chwang Censorship Wouldn't Let Him Answer Mr. Conger.	May 13, 1904
sm_55428_1077-18020.xml	An Artistic Advance Upon "The County Chairman." FRESHWATER COLLEGE COMEDY A Charming Production, and an Undistinguished Company Admirably Drilled.	Sep 21, 1904
sm_55428_1077-18862.xml	Plan to Mobilize the Class

sm_55428_1078-32534.xml	To Receive $3,000 for Two Performances -- "Salome" Barred by Censor. REJANE IN VAUDEVILLE lan Forbes-Robertson to Tour America -- Gertrude Elliott Also Coming and Will Join Husband's Company.	Jan 30, 1910
sm_55428_1078-32811.xml	St. Petersburg, However, Accepts an Odessa Dispatch with Caution.	Jul 2, 1905
sm_55428_1078-32988.xml	Feb 27, 1905	19050227
sm_55428_1078-33888.xml	Nov 6, 1905	19051106
sm_55428_1078-34539.xml	Methods and Conditions of Observation of an American Sympathizer Assailed.	Feb 24, 1904
sm_55428_1078-35149.xml	May 3, 1905	19050503
sm_55428_1078-35457.xml	This Writer Thinks Little Girl Was Not Right in Saving Lives by Lie.	Apr 4, 1904
sm_55428_1078-3559.xml	HORSE RAN OFF WITH PAY. He Dropped Dead, and Most of the Money Was Recovered.	Jul 9, 1905
sm_55428_1078-36185.xml	Apr 22, 1906	19060422
sm_55428_1078-3653.xml	Revenge, Says Playwright -- Suggests King Make Him a Duke.	Jun 26, 1909
sm_55428_1078-36975.xml	Some Interesting Experiments With the 

sm_55428_1079-43515.xml	A Significant Book About the Italian Novels and Novelists by Joseph Spencer Kennard.*	Jun 30, 1906
sm_55428_1079-43846.xml	Mob More Furious -- Peasants Have Joined the Rioters. THE OFFICIALS FOREWARNED Rumors of a Coming Outbreak Circulated a Fortnight Ago -- Thirty Killed, 80 Wounded Thursday.	Jun 16, 1906
sm_55428_1079-44318.xml	Declares Frick Committee Convicted Him Without a Hearing. HE WAS HAMPERED BY CUSTOM Sought to Change Equitable Methods Gradually -- Denies Part in Improper Syndicates.	Jun 4, 1905
sm_55428_1079-44624.xml	Mar 15, 1903	19030315
sm_55428_1079-44670.xml	Paul Dunbar and Other American Versifiers -- A New Book by William Watson.	Dec 5, 1903
sm_55428_1079-44918.xml	Nov 14, 1904	19041114
sm_55428_1079-45029.xml	BOY'S BATTLE WITH RUNAWAYS Little Alexander Stewart Crawled Along Pole of Wagon and Dragged at Horse's Bridle. TALESMEN FEAR THE MAFIA. Coroner Has Difficulty Getting a Jury in the Barrel Murder Case -- Italian Threatened. JEWISH MASSAC

sm_55428_1080-8992.xml	Return to a Constitutional Regime Is Granted. DIET SUMMONED AT ONCE Reactionary Senators Forced to Resign -- Students Honor Schaumann's Memory.	Nov 1, 1905
sm_55428_1080-9562.xml	Feb 3, 1905	19050203
sm_55428_1080-9670.xml	The Supposed "Journal" of a Russian Prisoner's Wife Reviewed by a Japanese.*	Apr 27, 1907
sm_55428_1080-9766.xml	Letters of Victoria Reveal the Formation and the Workings of the Mind of a Sovereign -- The Family of Professional Rulers As Practical Politicians. MAXIMS OF THE KING OF THE BELGIANS Evolution of the Young Queen Under Tutelage of the Continental Leopold and the English Melbourne.* SELF-REVEALING LETTERS OF QUEEN VICTORIA. INTIMATE ACCOUNT OF THE BUSINESS OF RULING.	Oct 26, 1907
sm_55428_1097-10195.xml	Army Representatives Inspect Animals in Kansas City.	Sep 6, 1914
sm_55428_1097-10204.xml	Oct 13, 1912	19121013
sm_55428_1097-10340.xml	Printing Soldier's Complaint Said to Have Caused Suspension.	Sep 28, 1914
sm_55428_1097-10483.xml	May

sm_55428_1097-33843.xml	Prepares Two Bills to Curb Dancing Which He Calls "Lascivious Orgies." SOME ALREADY CLOSED Several Places, Anticipating Visit of License Inspectors, While Serving the "Tea" Bar the "Tango."	Apr 5, 1913
sm_55428_1097-34144.xml	Clemenceau Quotes His Words to Put Blame for War on Kaiser.	Nov 10, 1914
sm_55428_1097-34226.xml	Germans Report Its Pilot Killed and Its Observer Captured.	Sep 22, 1915
sm_55428_1097-344.xml	While Older Folk Dally Over Prosaic Food, They Find Excitement Worthy of Haroun al Raschild's Capital Right Here in New York.	Aug 2, 1914
sm_55428_1097-34432.xml	Seek Injunction in England to Prevent Publication of a "Romance" of Their Family. WATERLOO TALE IS REVIVED Story of How Nathan Used Advance News of Result Declared Libelous, but Judge Refused Injunction.	Nov 28, 1912
sm_55428_1097-34621.xml	Sep 9, 1913	19130909
sm_55428_1097-34625.xml	REPLIED, BUT SAILED AWAY " She Answered," Officer Boxhall Tells Senate Committee Captain Said. STEWARDS OF SAME

sm_55428_1098-15759.xml	Would Monroe Doctrine Be Respected in Case of German Victory?	Nov 10, 1914
sm_55428_1098-16068.xml	Says Germany Must Not Let America Wrest Submarine Weapons from Her. CHANCELLOR IS ASSAILED Von Tirpitz Supporters Will Make "Frightfulness' an Issue at Today's Reichstag Session.	Mar 15, 1916
sm_55428_1098-16241.xml	Jun 8, 1916	19160608
sm_55428_1098-16486.xml	Censor at Cassel Forbids Its Production -- Author Not Worried.	Jul 3, 1913
sm_55428_1098-16548.xml	Our Government Powerless to Demand Relief, but Will Press Informal Negotiations.	Aug 6, 1915
sm_55428_1098-16610.xml	Ban on Code Messages Clogs the Lines with Long Communications. THERE IS NO DELAY HERE But Strict Censorship in France and England Holds Up Messages in Europe.	Aug 17, 1914
sm_55428_1098-16620.xml	Mass Attacks are irresistible, but Allies Contest Fiercely.	Sep 4, 1914
sm_55428_1098-16680.xml	New Army Pouring Through Warsaw to Retrieve Check by the Germans. RAILROAD SYSTEM IN PERIL Capture of Lodz T

sm_55428_1098-33866.xml	Municipal Commission Superintends Publication of The News, in Which All Parties Have a Voice, DISCUSSES PUBLIC ISSUES Paper Has Advanced from 8 Pages with 40000 Circulation to 12 Pages with a Circulation of 60,000 Copies,	Jul 14, 1912
sm_55428_1098-33870.xml	" Imperial Murderer" Assailed by Archdeacon of London, Who Tells of Children Slain.	Sep 13, 1915
sm_55428_1098-33890.xml	London Diplomats and Newspapers Point Out Some of the Difficulties in the Way. EXPECT FIGHT TO FINISH Say Huerta Will Make Impossible Conditions, Such as Indemnity for Those Killed at Vera Cruz.	Apr 27, 1914
sm_55428_1098-33939.xml	Dec 25, 1920	19201225
sm_55428_1098-33945.xml	Sep 6, 1914	19140906
sm_55428_1098-3406.xml	Men Like Him, Says Alderman Folks, Indirectly Responsible for the Loss of Life. PRESENT LAWS INADEQUATE Under Them Similar Panics May Occur in Any One of 800 Other Moving Picture Houses.	Feb 4, 1913
sm_55428_1098-34097.xml	Called "A New Peace Kite" -- Asquith's Guildhall De

sm_55428_1098-6869.xml	Woman Left Box at Sing Sing for New York Convict.	Dec 28, 1920
sm_55428_1098-7844.xml	But Public Can and Does Condemn the Board of Protectors Who Framed It. SKELETONS IN ALL CLOSETS And One Speaker at the Hearing to Remove Names Says There Are Some in the Protectors.	Mar 13, 1914
sm_55428_1098-8178.xml	G.L. Sterling, Acting, Supports Ordinance Which Comes Before Aldermen To-day. OPPOSES TWO OTHER PLANS Morrison's Would Continue Dangers, He Says, and Nicoll's Censorship Is Not Necessary.	Mar 11, 1913
sm_55428_1098-8374.xml	Proof Being That the Devil Is Loose in Soldiers Generally, War Babies Are Immemorial and Free Speech Is Dangerous.	Jun 3, 1915
sm_55428_1098-8524.xml	Zeppelins the Most Popular Topic; Soldiers' "Godmothers" Second.	Apr 1, 1916
sm_55428_1098-8981.xml	An Annotated List of Two Hundred and Fifty Best Books for Christmas Reading, in All Branches of Literature, Classified and Arranged Alphabetically According to the Authors TWO HUNDRED AND FIFTY BEST 

sm_55428_1099-26499.xml	Gen. Herrera and Staff Greet Villa's Pursuers After 100-Mile Ride in Desert. THEIR GARB PICTURESQUE Gaudy Accoutrements on Man and Beast, but No Matches -- Hardtack Tin His Dais. ASSURE PERSHING OF CO-OPERATION.	Apr 14, 1916
sm_55428_1099-27094.xml	To be Shot if They Harbor Enemies ;- Urged to Welcome the Kaiser.	Aug 16, 1914
sm_55428_1099-27146.xml	Details of the Warm Welcome Marseilles Gave to the Far East's Fighting Men. QUICK WORK IN LANDING Thousands of Fighting Men Disembarked in a Few Hours Without Accident.	Oct 3, 1914
sm_55428_1099-27224.xml	To be "Invincible" Dominated by "Humanity," He Says Is Her Future. LOOKS FOR REMADE NATION Text of Article Drawn from the Discovery Made by Times Correspondent Visiting the Trenches.	Apr 18, 1915
sm_55428_1099-27238.xml	Believes Good Relations Assured -- Berlin's Efforts to Prevent a Break Confirmed. OFFICIAL LID ON COMMENT Government Wants No Press Outbreak Over Vienna's Allusion to Munitions Shipments. GERMANY PLE

sm_55428_1099-44893.xml	All Nations Sick of Being Lured to Death, Says Scheidemann. BAR SUBMARINE DEBATES Budget Committee, Unable to Agree on a Policy, Advises Reichstag Not to Discuss It. CONFIDENT OF THE FUTURE Satisfaction Expressed with Military and Naval Achievements and Loan Subscriptions.	Oct 13, 1916
sm_55428_1099-45050.xml	Parliamentary Insurgents Face Defeat in Attempts to Discredit Him and Millerand.	Aug 16, 1915
sm_55428_1099-45052.xml	Prosecuted for the Publication of a Letter Which Gave Offense to France. WRITER ALSO A DEFENDANT Said That Last French Reserves Were out -- Letter Held to Have Aided the Germans.	Jun 1, 1915
sm_55428_1099-45220.xml	Nov 24, 1914	19141124
sm_55428_1099-45272.xml	5,000 East Siders Throng Information Clearing House Seeking Words of Hope. THOUSAND NAMES READ OUT Many Hear of Loved Ones Abroad, Some Dead, Some in Jail, Some Scourged Away. BUT ALL NEWS IS NOT BAD Cheers Greet Recognitions as Lists Are Gone Over ;- Yesterday's Work Toward Relief Fun

sm_55428_1100-16126.xml	Denies Discrimination Against Teutonic Allies, as Alleged by Some Partisans Here. TAKES UP 20 CHARGES And States the Administration's Position and Action on Each in Detail. OUR MARKETS OPEN TO ALL He Points Out That It Is the Belligerents' Place, Not Ours, to Stop Contraband at Sea. SEES SOURCE OF COMPLAINT Says British Superiority at Sea Has Interrupted Trade -- Calls Our Protest Sufficient Answer. THIS NATION FAIR, BRYAN ASSERTS	Jan 25, 1915
sm_55428_1100-16298.xml	Dr. Enrique Olaya Herrera, ex-Minister of Foreign Affairs of Colombia, Says Latin-American Republics Are Neutral at Heart ;- Fine Trade chance for U.S. DR. OLAYA HERRERA ON SOUTH AMERICA	Dec 6, 1914
sm_55428_1100-16359.xml	Pontiff Fears Destruction of Vatican Treasures in Event of Revolution -- Reluctant to Criticise Germany Until He Knows the Whole Truth About Horrors of War.	Jun 22, 1915
sm_55428_1100-16421.xml	Aug 23, 1914	19140823
sm_55428_1100-16492.xml	Sep 24, 1920	19200924
sm_55428_1100-16641

sm_55428_1100-28794.xml	Trades Federation Orders Strike -- Rand Miners Vote to Join It -- Martial Law. MAY SEND NATIVES HOME Government to Return 200,000 to Their Kraais if Miners Go Out, and This Would Ruin Industry.	Jan 14, 1914
sm_55428_1100-28837.xml	Dec 26, 1916	19161226
sm_55428_1100-28949.xml	Oct 19, 1920	19201019
sm_55428_1100-2913.xml	Prof. Brandenburg Renews Demand That the Chancellor Outline His Conditions. BERHARD JOINS ATTACK Leaders Say Bethmann Hollweg Will Lose Public Confidence by Continued Silence.	Jul 12, 1916
sm_55428_1100-29660.xml	Some Remarkable Ones of Known and Obscure Origin in England.	Apr 26, 1914
sm_55428_1100-29802.xml	Paris Press Sure He Inherited Disease That Killed His Father.	Jan 2, 1916
sm_55428_1100-30216.xml	Dec 24, 1914	19141224
sm_55428_1100-30412.xml	Will Have Hereditary Monarchy and a Constitution, Says Proclamation of Warsaw Governor.	Nov 5, 1916
sm_55428_1100-30455.xml	20,000 Plainly Hear Wagner's Opera with Metropolitan Stars.	Jun 7, 1916
sm_

sm_55428_1100-42125.xml	Officials and Publishers Form at Chicago New Department of Associated Clubs. SET STANDARD FOR PRESS Religious Newspapers Resent an Attack by New Yorker -- Editor Keeley Praises Agents' Work.	Jun 23, 1915
sm_55428_1100-42192.xml	Former "Spy" Accused of Attempting Extortion on Countess von Bernstorff. OFFERS LETTERS FOR $3,000 Threatened Publication of Embarrassing Secrets, but Letters Were Innocent. EMBASSY MADE COMPLAINT Washington Police Detective Overhears Negotiations and Makes the Arrest. SEIZE DR. GRAVES AS A BLACKMAILER	Nov 12, 1916
sm_55428_1100-4226.xml	J. O'Donnell Bennett Describes the Desolation Thirty Miles West of Warsaw. MANY PLACES OBLITERATED Fine Trenches, Built to Last for Long, Abandoned by the Russians. PEOPLE ARE COMING BACK Cheerful if Home Consists Only of Half a Chimney, a Brick Stove, and Trees Around the Ruins.	Oct 24, 1915
sm_55428_1100-42411.xml	James O'Donnell Bennett Describes a Ride Among the City's Fleeing Refugees. THE SIGHTS OF 

sm_55428_1102-27359.xml	Not Even Allowed to Communicate Privately With Home Government. DENIES CONFESSION OF PLOT But Makes No Explanation of Letter Proposing to Tie Up Munition Plants. SOUGHT TO AID NATIONALS Enlarges Upon Plans to Get Other Work for Them ;- Defends Archibald as Messenger.	Sep 19, 1915
sm_55428_1102-27429.xml	Deputies Resent Suppression of Criticism of United States. OFFICIALS GERMAN ATTITUDE ON PEACE	May 27, 1916
sm_55428_1102-27614.xml	Oct 7, 1915	19151007
sm_55428_1102-27891.xml	Line Which the Central Powers Must Defend in Europe Now Stretches 1,750 Miles. HAVE 10,600,000 MEN NOW Entente Armies Aggregate 24,000,000 ;- Strategy Likely to be Followed by Rumania.	Aug 29, 1916
sm_55428_1102-27910.xml	Foreign Singers Will Not Be Available if Conflict Lasts Long, Gatti-Casazza Says. HARD TO GET ARTISTS NOW Caruso, Rejuvenated by Drinking from Ancient Italian Spring, Also Returns on the Lafayette.	Oct 17, 1916
sm_55428_1102-27967.xml	Oct 7, 1914	19141007
sm_55428_1102-280

sm_55428_1102-43330.xml	Particularly Why Should the German Solution Be Thrust by Intelligent Might Upon People Unwilling to Receive It?	Aug 16, 1915
sm_55428_1102-43399.xml	Present Anti-Liberal Regime's Internal and International Action Objected To. TERRORISM BY MILITARY Budapest Government Makes Threat to Close Frontier Against West Hungary. ASSAULT COUNT ESTERHAZY. Plot to Bring Ex-Emperor Back to Hungary Foiled by a Consul. POLES AWAIT RED ATTACK. Bolsheviki Still Bringing Up Large Forces to Frontier.	Feb 23, 1920
sm_55428_1102-43712.xml	Apr 4, 1915	19150404
sm_55428_1102-4416.xml	This Government to Assist in Maintaining Neutrality of the Service.	Nov 16, 1916
sm_55428_1102-44242.xml	Jun 2, 1916	19160602
sm_55428_1102-44437.xml	Boisterous Farce from the French Presented There by Ned Wayburn. ORIGINAL BY PAUL GAVAULT Crude Adaptation of "Ma Tante d'Honfleur" Is Noisily Played and Received.	May 18, 1915
sm_55428_1102-44630.xml	Uncertainty in Rome Political Circles as Reopening of Parl

sm_55428_1103-15046.xml	Navy Department Makes Known Facts, Following Reports of British Embassy Protest. OUR OFFICERS IN CHARGE Will Be Used as a Receiving Station Only, Beginning Its Service Today.	Nov 18, 1915
sm_55428_1103-1518.xml	Republicans Have Already Chosen 702 of Their 985 Delegates to Chicago. 21 PLEDGED TO ROOSEVELT Colonel May Get Pennsylvania's 76 and 12 from New York -- A First Ballot Line-Up.	Apr 29, 1916
sm_55428_1103-15247.xml	Sep 23, 1915	19150923
sm_55428_1103-15266.xml	Ex-Ambassador Happy in His Address to 500 Women Friends of France. COUPLES TWO WAR HEROES Finest Way to Celebrate Washington's Birthday, He Says, Is in Conjunction with Lafayette.	Feb 23, 1916
sm_55428_1103-15329.xml	London Papers Say His Attacks on the Ministry Are Aiding the Enemy. BLUNDERS OF WAR EXPERTS The London Times's Military Critic's Errors Pointed Out -- Said Namur Would Hold Out 3 Months.	May 1, 1915
sm_55428_1103-15381.xml	Oct 7, 1921	19211007
sm_55428_1103-15428.xml	Recent Volumes That 

sm_55428_1103-32210.xml	Bathrooms Used as Bedrooms in Even the Largest Hotels in the Capital. VAST WAR RELIEF CENTRE Everybody, from Imperial Family Down, Aiding Sick and Wounded Soldiers and Their Families.	Mar 12, 1916
sm_55428_1103-32361.xml	President Starts Prompt Inquiry Into Ancona Disaster. CABLES FOR ALL DETAILS Will Seek All Facts as to Liner's Conduct Before Making Protest. GERMAN PLEDGE BINDING Austria Regarded as Equally Responsible to Us for Safety of Americans at Sea. WASHINGTON FEARS CRISIS OVER ANCONA	Nov 11, 1915
sm_55428_1103-32689.xml	Government Decides Banks May Keep Test Words Secret.	Oct 31, 1916
sm_55428_1103-32725.xml	Deliberate Infection of Prisoners with Tuberculosis by German Medical Authorities Revealed to Her in Paris.	Sep 25, 1916
sm_55428_1103-33215.xml	War Censor Advises Americans to Write Messages in Full.	Sep 15, 1916
sm_55428_1103-33354.xml	Apr 22, 1916	19160422
sm_55428_1103-33381.xml	Whole Diplomatic Corps Threatens to Abandon Country, Cutting All T

sm_55428_1103-46449.xml	President of Marconi Co. Asserts Secretary of Navy Has No Power to Control Wireless. UP TO DEPT. OF COMMERCE Invites Legal Action on Part of the Government to Decide Which Is Correct.	Sep 11, 1914
sm_55428_1103-46547.xml	Jul 16, 1916	19160716
sm_55428_1103-46744.xml	Beulah Marie Dix Tells of the Beginnings of Her Impressive New War Drama Now at the New Amsterdam Theatre.	Sep 26, 1915
sm_55428_1103-46833.xml	Hale Denies Wilson Is Stronger Than His Party ;- Finds Republican Gains. A.P. MOORE SEES WILLCOX Pittsburgh Progressive Says Eight-Hour Law Will Not Help Wilson In Pennsylvania.	Sep 17, 1916
sm_55428_1103-47006.xml	Trying to Raise Money by Internal and Foreign Loans.	Feb 12, 1913
sm_55428_1103-47015.xml	One-Observer Who Is Convinced That France and England Had Just as Soon Play Poker for the Pieces of the Ottoman Empire Without Our Sitting in the Game	Jan 25, 1920
sm_55428_1103-47317.xml	Oct 7, 1920	19201007
sm_55428_1103-47538.xml	Raid of Dec. 29 Repulsed by

sm_55428_1105-5355.xml	John McClain of Peekskill Decorated for Hurling LiveBomb Into a River.WAS DROPPED BY GERMANFirst American Soldier to Win Honor Served with Pershing's Forceson the Border.	Sep 30, 1917
sm_55428_1105-5463.xml	Reports of Movement to Proclaim Carranza Minister Lawful Successor.	Jul 10, 1920
sm_55428_1105-5719.xml	Commission Appeals to Americans to Help in Feeding a Million Destitute. PRIEST ACCUSES GERMANS Father Stillemans Charges Thefts, Extortion, Death Sentences and Deportations.	May 15, 1916
sm_55428_1105-5806.xml	Kaiser's New Chancellor Will Also Become the Premier of Prussia. WALDOW, FOOD CHIEF, QUITS Von Payer to be Vice Chancellor-- Reassembling of the Reichstag Is Hastened.	Nov 2, 1917
sm_55428_1105-5962.xml	Aug 27, 1920	19200827
sm_55428_1105-6139.xml	Nov 28, 1916	19161128
sm_55428_1105-6152.xml	Jun 15, 1915	19150615
sm_55428_1105-6162.xml	Strict Censorship Now Imposed on All Press Dispatches.	Apr 12, 1914
sm_55428_1105-6189.xml	Dyestuffs Being Rushed from

sm_55428_1106-23563.xml	Kaiser Promises "Mailed Fist" Will Restore Constantine	Jun 16, 1917
sm_55428_1106-23907.xml	State's New Censors Want to Be Fair, They Say, Even on Bathing Girls Virtue Triumphant Preferred. A Case in Point. Mrs. Hosmer's Work.	Sep 4, 1921
sm_55428_1106-24051.xml	Restored in New Form After Some Who Had Voted Against It Had Left the Floor. ACTION IS CONDEMNED As Violating "Gentlemen's Agreement" Which Covered First Vote. JURY TRIAL PROVIDED FOR President to Proclaim the Character of Information That May Be Useful to the Enemy. Text of Gard Substitute. Raises Question of Intent. CENSORSHIP PUT THROUGH THE HOUSE Amendments Knocked Out. EMBARGO CLAUSE CHANGED. Senate Adopts a Substitute Restricting President's Power.	May 5, 1917
sm_55428_1106-2415.xml	Samson Reported Killed in Raid on Germans in Belgium.	Feb 5, 1915
sm_55428_1106-24298.xml	Jul 23, 1920	19200723
sm_55428_1106-24369.xml	Bishop Wilson Tells New York Conference It Is "Unmanly" to Assail Its Work. FIVE YO

sm_55428_1109-3537.xml	Vienna Professor Attacks Cruelties of Zeppelins and U-Boats.	Feb 4, 1916
sm_55428_1109-35387.xml	Admiral Benson and Secretary Alexander Speak at League Luncheon. MAIN FACTORS ARE CITED American Built and Manned Fleet, with Own Fuel and Trade Routes, Advocated.	Apr 13, 1920
sm_55428_1109-35475.xml	Bomb Their Way Along Hindenburg Line to West;-Many Troops Enjoying Repose. Shelling Lens Buildings. BRITISH EXTENDING BULLECOURT GAINS Cricket Match Behind Lines.	May 21, 1917
sm_55428_1109-35525.xml	Department of Justice Wants Spy Suspect Held While Investigation Goes On. HE DENIES BIGAMY CHARGE Train Expects to Produce Two Women as Wives of the German-American.	Oct 15, 1915
sm_55428_1109-35705.xml	Political Censorship at Maximum of Rigor, Despite theReichstag Warning.	Sep 29, 1917
sm_55428_1109-36351.xml	Joint Conference of Labor Called for Wednesday to Prepare for General Tie-up. MANY LOCALS MARK TIME Leaders Say 40 Per Cent. of Organized Workers Are Pledged to Suspen

sm_55428_1109-9304.xml	Folly, He Says, to Talk Now About Specific Plans for Treaty Action. FOR NON-PARTISAN COUNCIL Senator Starts Today for St. Paul to Address Farmers at Minnesota State Fair. Not Expected to Answer Cox. Chicago Expects to See Harding.	Sep 7, 1920
sm_55428_1109-9315.xml	Wonders What Sir Gilbert Parker Really Wrote to Him.	Aug 23, 1915
sm_55428_1109-9551.xml	Federation Declares San Francisco Platform More Progressive Than That of Republicans. ISSUES ANALYSIS OF PLANKS Holds They " More Nearly Approximate the Desired Declarations of Human Rights." Text of Labor Statement. LABOR COMMENDS DEMOCRATS' STAND Collective Bargaining. Injunctions in Labor Cases. Tribunals for Labor Disputes. Free Speech and Assemblage. Enforcement of Seamen's Act. Child Labor and Protection. Reduction of Living Cost. Immigration and Labor. Hours of Employment. Workmen's Compensation. Products of Convict Labor. Federal Courts. Mexican Intervention. Conclusion.	Jul 15, 1920
sm_55428_1109-9897.xml	

sm_55428_1110-30869.xml	First Aero Squadron Will Accompany Army Into Mexico as Scouts. MOVING TROOPS TO BORDER Those Not Sent with Punitive Expedition Will Guard the Line. MEXICAN FORCES ACTIVE Want to Catch Villa Before the Americans Can -- Protecting Chihuahua Mormons. FLIERS TO AID TROOPS IN SEARCH FOR VILLA	Mar 12, 1916
sm_55428_1110-3087.xml	Episcopal Convention Stands Behind Government on Liquor Measures.	Nov 16, 1917
sm_55428_1110-31102.xml	Aug 17, 1920	19200817
sm_55428_1110-31472.xml	Lord Robert Cecil Tells Foreign Correspondents His Idea on News Curbs	Feb 19, 1916
sm_55428_1110-32205.xml	Ex-Ambassador Happy in His Address to 500 Women Friends of France. COUPLES TWO WAR HEROES Finest Way to Celebrate Washington's Birthday, He Says, Is in Conjunction with Lafayette.	Feb 23, 1916
sm_55428_1110-32233.xml	Financier's Criticisms of Germans in 1915 Placed in Official French Files.WRITTEN TO HIS RELATIVE Of German Birth, New York Banker Took Kaiser's Generals to Task for War of Frigh

sm_55428_1111-11476.xml	Theatre Commerce Chamber Is Against Exploiting Sensationalism, Says Secretary.OTHER OWNERS BAR FILM Primex Corporation, However, Continues to Seek Broadway House for the Piece.	Dec 23, 1921
sm_55428_1111-11667.xml	Jul 28, 1922	19220728
sm_55428_1111-11813.xml	Feb 6, 1920	19200206
sm_55428_1111-12133.xml	Jul 2, 1916	19160702
sm_55428_1111-13134.xml	Mar 10, 1921	19210310
sm_55428_1111-13313.xml	Stocks Have a Bad Day on Unfavorable News and Rumors.	May 3, 1917
sm_55428_1111-13541.xml	Sep 15, 1920	19200915
sm_55428_1111-13978.xml	Mar 24, 1920	19200324
sm_55428_1111-14089.xml	Mar 10, 1921	19210310
sm_55428_1111-14278.xml	Royal R. Keeley, First a Guest, Then a Prisoner, Saw People Exploited and Country Brought to Ruin His Arrival Capitalized. Says Workmen Won't Work. Export Plans Impractical. Trotzky Uninteresting.	Nov 20, 1921
sm_55428_1111-14693.xml	Jersey Alliance to Fight Candidates Opposed to Their "Interests."	Apr 3, 1916
sm_55428_1111-14853.xml	May 4, 1921	1921

sm_55428_1111-43540.xml	Socialists and Labor Unions Call Strike and Demonstration in Inflammatory Manifesto. ANOTHER MURDER ARREST Ex-Naval Cadet Charged With Providing Pistol Used in Shootingof Dr. Rathenau. Another Arrest in Rathenau Case. Bill to Expel Ex-Royalties	Jul 2, 1922
sm_55428_1111-43681.xml	Jan 9, 1921	19210109
sm_55428_1111-43765.xml	What Russia Reads Today	Oct 30, 1921
sm_55428_1111-43787.xml	Advised His Withdrawal, As Did Groener, Prussian War Minister.FINANCIAL PRESSURE USED Soldiers Pay Held Up--Ministers and Officials Refusedto Take Kapp's Orders. STRIKE POTENT IN RESULT Has Spread Widely Throughout Germany and BeenVery Effective. Kapp Regime Impossible, Groener Said. Sixty Reported Killed in Berlin. Serious Demonstrations by Radicals. Centrists Brand Kapp as Traitor.	Mar 17, 1920
sm_55428_1111-43929.xml	Paris Press Sure He Inherited Disease That Killed His Father.	Jan 2, 1916
sm_55428_1111-44230.xml	Convention Ends With Endorsement of Disarmament Program by 16,000 D

sm_55428_1112-24047.xml	Dec 10, 1921	19211210
sm_55428_1112-24157.xml	SUMMER SALES AND EXHIBITIONS A Painting by George Luks. Newark Museum Radio Talks. The Woodstock Art Association.	Jun 18, 1922
sm_55428_1112-24543.xml	Commander Kail, Lieut. Commander Boucher and AttorneyFound Guilty by Court.KAIL ASSUMED GOVERNMENTSet Up Censorship, Reinstated Deposed Natives and Suspended Courts After Terhune's Suicide.	Dec 12, 1920
sm_55428_1112-24931.xml	Socialist Deputy Demands a Relaxation of Rigors of Martial Law. FAVORITISM IS ALLEGED He Says Opposition Newspapers Are Curbed, While Government Organs Have Free Rein. From a Staff Correspondent. Special Cable to THE NEW YORK TIMES.	Jan 11, 1916
sm_55428_1112-25339.xml	Warning of It Sent to Foreign Minister by a Consul in Spain.	Oct 27, 1921
sm_55428_1112-25474.xml	Oct 15, 1922	19221015
sm_55428_1112-25488.xml	Tells City College Students Co-operatives Have Anything to Sell.	Mar 5, 1920
sm_55428_1112-25701.xml	Japan Hears of Five Ships Being Sunk 

sm_55428_1112-49368.xml	He Calls Harrison's Resolution "Futile Bad Manners," and Author Withdraws It. SAYS POWERS MUST DECIDE Asserts Senate's Constitutional Rights of Review Preclude Any Secret Agreements. VOTE $200,000 FOR PARLEY Shipping Board Deficiency Bill of $48,500,000 Is Passed Without Restrictions on Salaries. Wants the Senate on Record. Danger of Closed Doors. Important Sessions Secret. Senate Passes $48,500,000 Bill.	Aug 24, 1921
sm_55428_1112-49472.xml	OPENING OF THE SCHOOLS. Arousing the Interest of Parents the Next Great Need. TAX RELIEF DELAYED. Continued Hold-Up of Business Revival Is Feared. Why He Leaves New York. Aid for War Sufferers. REWRITING HISTORY. More Comment on the Knights of Columbus Proposal. "Reich" Equals "Commonwealth."	Sep 9, 1921
sm_55428_1112-49833.xml	Censors of Lake Shore Go Armed With Needles and Pins.	Jun 19, 1921
sm_55428_1112-5073.xml	Education Measures Sharply Attacked by Professor Giddings-- Lusk Defends Them	May 2, 1920
sm_55428_1112-5224.x

sm_55428_1113-27294.xml	Risk of French Occupation Put on Munich Cabinet if It Refuses to Disarm. ROYALISTS IN SECRET PLOT Propaganda Planned Against Disarmament and Indemnity and toOverthrow Republicans.	Feb 9, 1921
sm_55428_1113-28158.xml	After Soldiers Get 14 Without Firing a Shot, Mexicans Fire on Motor Cars. CROSS RIO AT BOQUILLAS Maj. Langhorne's Men Find Loot in a Captive's Store, Take Bandits by Surprise. RAIDERS CAPTURED IN A CAVALRY DASH	May 12, 1916
sm_55428_1113-28600.xml	Resolution Fixing Sunday, June 5, for Plea by Churches Voted by General Assembly. WOMEN ELDERS PLAN LOST Office of Permanent Clerk Abolished and Plans Are Perfected for Election of a Stated Clerk. Unity Proposal is Lost. Committee Is Organized.	May 21, 1921
sm_55428_1113-28661.xml	Nov 19, 1922	19221119
sm_55428_1113-29396.xml	Dispatch to Bethmann Organ Hints of 'Psychological Moment' for Offer by Entente. REICHSTAG RECESS; STILL TALK OF PEACE Adjournment Virtually Forced. Czernin Goes to See Bethmann Again.

sm_55428_1113-7585.xml	Governor Signs Meyer-Martin Bill Before Starting on Two Weeks' Vacation. HAS 200 MEASURES LEFT To Announce Decision on Movie Censorship and Boxing CommissionBills Here Today.	May 14, 1921
sm_55428_1113-7709.xml	Oppponents of Political Censor for Stage Seek 300 Observers.	Apr 18, 1922
sm_55428_1113-7831.xml	Jan 12, 1916	19160112
sm_55428_1113-7939.xml	He and His Official Advisers Favor Representation in the Two Houses. SUPPORT LAW FOR CHANGE Would Attend Sessions to Speak on Questions Relating to Departments. PENDING BILLS COVER PLAN Modification of British System Is Provided For in Three Measures. For Attending Only When Needed. Membership Status Not Sought. HARDING SUPPORTS CABINET SHARING Harding for Cabinet Freedom. One Bill Includes Board Chiefs. Drift of Movement in the Past. Washington and Jefferson Attended. Madison Opposed the System.	Jun 24, 1922
sm_55428_1113-810.xml	Governor to See Program Completed With AdjournmentProbable on Saturday.OPPOSITION IN SE

sm_55428_1114-35241.xml	Apr 2, 1921	19210402
sm_55428_1114-35692.xml	But Is Opposed to Unlawful Search and Seizure as Practiced by Police. REPLIES TO WOMEN VOTERS Haskell Asks How He Stands on the Whole Question of Prohibition. ATTACKS 'MOVIE' CENSORS Judge Asserts Blue Law Fanatics Are Destroying What Freedom the Prohibitionists Overlooked. Says It's Not an Issue.	Aug 31, 1921
sm_55428_1114-35720.xml	Aug 27, 1922	19220827
sm_55428_1114-36938.xml	Actress Will Present a Petition to the Governor.	Apr 24, 1916
sm_55428_1114-37210.xml	Nov 27, 1921	19211127
sm_55428_1114-37293.xml	Marks of French Supervision on Aleppo Journal Which Printed the Account.	Jun 2, 1922
sm_55428_1114-37332.xml	Sep 18, 1921	19210918
sm_55428_1114-38850.xml	President Leguia Is Declared to Have Usurped Powers and Exiled Opponents.	Apr 23, 1921
sm_55428_1114-39937.xml	President of Drama League Believes Producers and Public AreImproving Plays.	May 7, 1922
sm_55428_1114-3996.xml	Jan 1, 1922	19220101
sm_55428_1114-39973

sm_55428_1116-47916.xml	Augustus Thomas Speaks	Aug 27, 1922
sm_55428_1116-47952.xml	Sharp Encounters on the Marne Cost Enemy Three Machines-- Fought Over German Lines.	Jul 7, 1918
sm_55428_1116-48272.xml	Nov 12, 1917	19171112
sm_55428_1116-48403.xml	British Socialist Leader Does Not, However, Expect a Revolution in Germany.	Mar 20, 1917
sm_55428_1116-48459.xml	Wants the Press Admitted to Meetings When Main Questions Are Considered.REQUEST TO DELEGATIONHarrison Resolution Is PassedAfter Dropping a Paragraph on Censorship. SENATE VOTES TO ASK PARLEY PUBLICITY Text of the Resolution. Says Subtle Diplomacy It at Work. Lodge Warns of Bad Manners.	Nov 9, 1921
sm_55428_1116-48680.xml	Fess Leads Pomerene in Late Returns by 6,000DONAHEY RUNNING AHEADDemocrat Has Majority of 26,000 for Governor--Beer Is Winning.LODGE IS BARELY WINNERDemocratic Reaction in BayState Imperils Him andGovernor Cox. LODGE'S PLURALITY LOW IN MASSACHUSETTS CONTESTS ARE CLOSE IN MASSACHUSETTS	Nov 8, 1922
sm_55428_1116-48

sm_55428_1117-26403.xml	Vice Society's Proposal to Censor Manuscripts Before Publication Is Opposed.SOME CLASSICS ATTACKEDLawrence Grant MentionsShakespeare's Sonnets, Byron,and "Swift's Obscenities."WRITERS EXPRESS VIEWS Lawrence S. Steiner Sees Moral Stagnation as Result ofRestrictions. Opposes a Pooh Bah Censor. Discussions May Stop. Duncan Sarcastic as to Plan.	Aug 6, 1922
sm_55428_1117-26732.xml	Sep 11, 1921	19210911
sm_55428_1117-2710.xml	Rabbi Reveals Unanswered Plea to Producer for Sake of Jews' Good Name. 'CLEAN UP OR FACE A CENSOR' "Demi-Virgin" Helping Drive the Stage Toward State Control, He Warns. Calls "Demi-Virgin" Garbage. Would Work for Censorship.	Mar 13, 1922
sm_55428_1117-27459.xml	British Retired Officer Reports Part of the German Losses.	Mar 11, 1917
sm_55428_1117-27558.xml	Would Muzzle the Press and Smother Criticism of Government, Johnson Declares.WATSON ATTACKS CREEL Reads Denver Editorials He Wroteand Characterizes Them "FoulSlanders" on Government. Fashion to

sm_55428_1117-48882.xml	Objects to Dr. Crafts's Plan for Federal Commission Without Consulting Producers. BROKE AGREEMENT, HE SAYS Former Conferences Arranged to Give Industry Time to Carry Out Reform Itself, He Asserts.	Mar 21, 1921
sm_55428_1117-49474.xml	KEMALISTS QUIT ERENKEUI Withdrawal Gives British Control of Long Stretch of the Narrows. TURKS ASKED TO PARLEY Harington Proposes Easing Chanak Situation by Altering. Anglo-Turkish Front. MEETING WITH KEMAL SOON But His Spokesman Says Turks Will Not Leave Neutral Zone Pending Negotiations. Large Forces of British Infantry Landed. Text of Kemal's Note to Harington. LET GREEK CRUISER PASS. British Released the Averoff on Pledge to Sail for Piraeus.	Oct 1, 1922
sm_55428_1117-49540.xml	Will Become Associate of Gustavus A. Rogers, Counsel for Fox Films.	Apr 4, 1921
sm_55428_1117-5010.xml	Army Could Be Equipped as Fast as It Could Be Used in Event of War. FIRST CALL ON NAVY LIKELY President Empowered by Army Bill to Take Over Any Plants f

sm_55428_1118-28460.xml	Theatre Commerce Chamber Is Against Exploiting Sensationalism, Says Secretary.OTHER OWNERS BAR FILM Primex Corporation, However, Continues to Seek Broadway House for the Piece.	Dec 23, 1921
sm_55428_1118-28946.xml	Firemen Save Some, But in One Case Wife and Two Children Are Injured.BOMB NEW SENATOR'S SHOPRory O'Connor Died Bravely and in Letter to Brother SaysHe Forgave Former Comrades. FOUR WERE SHOT TOGETHER Appointment of the Duke of Abercorn as Governor General forUlster Is Announced. Four Were Executed Together. Forgives Former Comrades. REPUBLICANS BURN HOMES IN DUBLIN Old Man Makes His Protest. Ulster Governor Is Named.	Dec 11, 1922
sm_55428_1118-29271.xml	Senate Judiciary Committee Fails to Remove Restriction on News Inquiries. LIFTS BAN ON CRITICISM Attempt to Liberalize Measure Merely Limits an Imaginary Power ;-Fight to be Carried to Senate.	Apr 18, 1917
sm_55428_1118-29459.xml	May 30, 1921	19210530
sm_55428_1118-29508.xml	Apr 25, 1921	19210425
sm_554

sm_55428_1118-4955.xml	Chancellor Refuses to Answer Principal Questions;-Plans an Address Tomorrow. KAISER CALLS WAR COUNCIL Hindenburg and Ludendorff Arrive in Berlin to Seethe Emperor. REVOLT IN CENTRIST PARTY Erzberger, One Leader, Attacks theAdmiralty and Demands a"No-Annexation" Peace. BETHMANN DODGES REICHSTAG QUERIES Press Argues for Reforms. Discussion Was Heated. "Quo Vadis, Germany?" Erzberger Threatened Chancellor. Majority Party Split Up. Crisis Expected Today.	Jul 9, 1917
sm_55428_1118-49723.xml	Even When Austrian "Reactionary Octopus" and His Satellites Were Supreme the Trend Toward Freedom Was Unmistakable.	Apr 8, 1917
sm_55428_1118-49850.xml	Board Now Co-operating with British and French Inspectors.	Dec 25, 1917
sm_55428_1118-5011.xml	Germans Accuse American Bankers of an "Offensive" to Depress Exchange Rates. CHARGE IS RIDICULED HERE Collapse Attributed to the Empire's Inflation Policy--Heavy German Gold Shipments Reported. Bankers Ridicule "Offensive" Talk.	Jun 22, 19

In [4]:
months = ["Jan", "Feb", "Mar", "Apr", "May", "Jun", "Jul", "Aug", "Sep", "Oct", "Nov", "Dec"]

In [18]:
years = {}

In [ ]:
for file in files:
    for month in months:
        if month in files[file][1]:
            year = files[file][1].split(", ")[1]
            break
        if month in files[file][2]:
            year = files[file][2].split(", ")[1]
            break
    if year in years:
        years[year] += 1
    else:
        years[year] = 1
    print(file + "\t" + year)

In [21]:
for line in open("1004-1119.txt"):
    try:
        name, date1, date2 = line.split("\t")
    except ValueError:
        print(line)
    for month in months:
        if month in date1:
            try:
                if date1.split(", ")[1].isdigit():
                    year = date1.split(", ")[1]
            except IndexError:
                continue
            break
        if month in date2:
            try:
                if date2.split(", ")[1].isdigit():
                    year = date2.split(", ")[1]
            except IndexError:
                continue
            break
    if int(year) in years:
        years[int(year)] += 1
    else:
        years[int(year)] = 1
        
    print(name + "\t" + year)

sm_55428_1004-11246.xml	1859
sm_55428_1004-12061.xml	1860
sm_55428_1004-12501.xml	1860
sm_55428_1004-12638.xml	1860
sm_55428_1004-12769.xml	1860
sm_55428_1004-13586.xml	1860
sm_55428_1004-13622.xml	1861
sm_55428_1004-13949.xml	1860
sm_55428_1004-13977.xml	1860
sm_55428_1004-14744.xml	1860
sm_55428_1004-15205.xml	1860
sm_55428_1004-15715.xml	1859
sm_55428_1004-15768.xml	1861
sm_55428_1004-1626.xml	1861
sm_55428_1004-16542.xml	1860
sm_55428_1004-16709.xml	1860
sm_55428_1004-17018.xml	1858
sm_55428_1004-17113.xml	1858
sm_55428_1004-17788.xml	1858
sm_55428_1004-17845.xml	1862
sm_55428_1004-1805.xml	1860
sm_55428_1004-18389.xml	1860
sm_55428_1004-19029.xml	1860
sm_55428_1004-19288.xml	1860
sm_55428_1004-19295.xml	1858
sm_55428_1004-19608.xml	1859
sm_55428_1004-21662.xml	1859
sm_55428_1004-22040.xml	1859
sm_55428_1004-24325.xml	1859
sm_55428_1004-25208.xml	1861
sm_55428_1004-2541.xml	1861
sm_55428_1004-26093.xml	1861
sm_55428_1004-2631.xml	1860
sm_55428_1004-26620.xml	1860
sm_55428_1004-2684

sm_55428_1019-34049.xml	1876
sm_55428_1019-34678.xml	1876
sm_55428_1019-35219.xml	1875
sm_55428_1019-35360.xml	1875
sm_55428_1019-35490.xml	1875
sm_55428_1019-36558.xml	1875
sm_55428_1019-37802.xml	1875
sm_55428_1019-38527.xml	1875
sm_55428_1019-39423.xml	1875
sm_55428_1019-39462.xml	1876
sm_55428_1019-39537.xml	1877
sm_55428_1019-39587.xml	1872
sm_55428_1019-41271.xml	1874
sm_55428_1019-43322.xml	1877
sm_55428_1019-43346.xml	1877
sm_55428_1019-43687.xml	1877
sm_55428_1019-43896.xml	1877
sm_55428_1019-46333.xml	1877
sm_55428_1019-46766.xml	1877
sm_55428_1019-48963.xml	1877
sm_55428_1019-4960.xml	1876
sm_55428_1019-5371.xml	1876
sm_55428_1019-7126.xml	1876
sm_55428_1019-9114.xml	1876
sm_55428_1019-9417.xml	1876
sm_55428_1019-9957.xml	1876
sm_55428_1020-10112.xml	1876
sm_55428_1020-10861.xml	1876
sm_55428_1020-11289.xml	1876
sm_55428_1020-11639.xml	1876
sm_55428_1020-12017.xml	1878
sm_55428_1020-12399.xml	1874
sm_55428_1020-13314.xml	1874
sm_55428_1020-140.xml	1874
sm_55428_1020-15734.xm

sm_55428_1035-38848.xml	1885
sm_55428_1035-39721.xml	1880
sm_55428_1035-39724.xml	1880
sm_55428_1035-39754.xml	1882
sm_55428_1035-40414.xml	1882
sm_55428_1035-40881.xml	1883
sm_55428_1035-40983.xml	1883
sm_55428_1035-41440.xml	1883
sm_55428_1035-42047.xml	1883
sm_55428_1035-45494.xml	1885
sm_55428_1035-4577.xml	1883
sm_55428_1035-46803.xml	1882
sm_55428_1035-47955.xml	1882
sm_55428_1035-48578.xml	1882
sm_55428_1035-49327.xml	1882
sm_55428_1035-5030.xml	1882
sm_55428_1035-6659.xml	1886
sm_55428_1035-6715.xml	1881
sm_55428_1035-7250.xml	1883
sm_55428_1035-8710.xml	1883
sm_55428_1035-929.xml	1884
sm_55428_1035-9536.xml	1884
sm_55428_1036-11308.xml	1884
sm_55428_1036-13029.xml	1884
sm_55428_1036-13733.xml	1885
sm_55428_1036-14358.xml	1886
sm_55428_1036-15413.xml	1886
sm_55428_1036-16307.xml	1885
sm_55428_1036-16694.xml	1887
sm_55428_1036-17430.xml	1884
sm_55428_1036-17656.xml	1885
sm_55428_1036-18558.xml	1884
sm_55428_1036-18977.xml	1886


sm_55428_1036-18977.xml	1886


sm_55428_1036-18977


sm_55428_1052-6489.xml	1893


sm_55428_1052-6489.xml	1893
sm_55428_1052-6691.xml	1893
sm_55428_1052-8051.xml	1893
sm_55428_1052-8171.xml	1893
sm_55428_1053-10659.xml	1893
sm_55428_1053-1365.xml	1893
sm_55428_1053-14598.xml	1894
sm_55428_1053-15277.xml	1894
sm_55428_1053-16440.xml	1894
sm_55428_1053-1657.xml	1895
sm_55428_1053-1705.xml	1895
sm_55428_1053-17375.xml	1895
sm_55428_1053-18168.xml	1895
sm_55428_1053-18228.xml	1895
sm_55428_1053-18362.xml	1895
sm_55428_1053-18828.xml	1895
sm_55428_1053-20944.xml	1895
sm_55428_1053-21127.xml	1895
sm_55428_1053-21654.xml	1895
sm_55428_1053-22313.xml	1894
sm_55428_1053-22437.xml	1894
sm_55428_1053-22883.xml	1895
sm_55428_1053-24604.xml	1895
sm_55428_1053-24981.xml	1895
sm_55428_1053-25123.xml	1895
sm_55428_1053-25322.xml	1895
sm_55428_1053-25602.xml	1895
sm_55428_1053-25676.xml	1895
sm_55428_1053-25733.xml	1895
sm_55428_1053-26918.xml	1895
sm_55428_1053-28408.xml	1895
sm_55428_1053-28736.xml	1895
sm_55428_1053-29487.xml	1894
sm_55428_1053-29895

sm_55428_1063-13002.xml	1898
sm_55428_1063-13518.xml	1898
sm_55428_1063-13656.xml	1898
sm_55428_1063-13832.xml	1898
sm_55428_1063-14635.xml	1899
sm_55428_1063-14763.xml	1899
sm_55428_1063-15001.xml	1899
sm_55428_1063-15120.xml	1899
sm_55428_1063-15252.xml	1899
sm_55428_1063-16688.xml	1899
sm_55428_1063-1768.xml	1899
sm_55428_1063-17726.xml	1899
sm_55428_1063-17740.xml	1901
sm_55428_1063-17881.xml	1900
sm_55428_1063-17898.xml	1900
sm_55428_1063-1810.xml	1899
sm_55428_1063-18827.xml	1899
sm_55428_1063-19040.xml	1901
sm_55428_1063-19266.xml	1899
sm_55428_1063-19440.xml	1899
sm_55428_1063-1945.xml	1899
sm_55428_1063-1962.xml	1900
sm_55428_1063-19992.xml	1900
sm_55428_1063-20012.xml	1898


sm_55428_1063-20012.xml	1898


sm_55428_1063-20012.xml	1898
sm_55428_1063-20809.xml	1898
sm_55428_1063-20940.xml	1898
sm_55428_1063-21005.xml	1898
sm_55428_1063-21491.xml	1899
sm_55428_1063-2152.xml	1899
sm_55428_1063-21630.xml	1898
sm_55428_1063-21689.xml	1898
sm_55428_1063-22063.xml	1898
sm_55428_1063-2

sm_55428_1070-38261.xml	1901
sm_55428_1070-39306.xml	1901
sm_55428_1070-39387.xml	1901
sm_55428_1070-39535.xml	1902
sm_55428_1070-3976.xml	1902
sm_55428_1070-39772.xml	1902
sm_55428_1070-40350.xml	1903
sm_55428_1070-41451.xml	1904
sm_55428_1070-4159.xml	1902
sm_55428_1070-42111.xml	1902
sm_55428_1070-42163.xml	1902
sm_55428_1070-42687.xml	1902
sm_55428_1070-43754.xml	1902
sm_55428_1070-43853.xml	1907
sm_55428_1070-4432.xml	1901
sm_55428_1070-44535.xml	1901
sm_55428_1070-44755.xml	1901
sm_55428_1070-44790.xml	1901
sm_55428_1070-44990.xml	1901
sm_55428_1070-45934.xml	1899
sm_55428_1070-45980.xml	1899
sm_55428_1070-46817.xml	1904
sm_55428_1070-46955.xml	1900
sm_55428_1070-47648.xml	1900
sm_55428_1070-47858.xml	1900
sm_55428_1070-48237.xml	1900
sm_55428_1070-48663.xml	1900
sm_55428_1070-48910.xml	1901
sm_55428_1070-49093.xml	1901
sm_55428_1070-49129.xml	1899
sm_55428_1070-49138.xml	1900
sm_55428_1070-49533.xml	1900
sm_55428_1070-49709.xml	1900
sm_55428_1070-49973.xml	1905
sm_55428_1070-499

sm_55428_1079-48425.xml	1905
sm_55428_1079-4906.xml	1905
sm_55428_1079-49121.xml	1905
sm_55428_1079-49610.xml	1905
sm_55428_1079-49857.xml	1905
sm_55428_1079-5364.xml	1905
sm_55428_1079-6304.xml	1905
sm_55428_1079-6679.xml	1905
sm_55428_1079-6982.xml	1905
sm_55428_1079-8960.xml	1907
sm_55428_1079-9049.xml	1905
sm_55428_1079-9296.xml	1905
sm_55428_1079-9724.xml	1905
sm_55428_1080-10416.xml	1905
sm_55428_1080-10855.xml	1905
sm_55428_1080-11462.xml	1905
sm_55428_1080-11569.xml	1905
sm_55428_1080-1164.xml	1905
sm_55428_1080-12835.xml	1905
sm_55428_1080-13144.xml	1905
sm_55428_1080-13246.xml	1905
sm_55428_1080-13279.xml	1907
sm_55428_1080-13430.xml	1907
sm_55428_1080-13571.xml	1907
sm_55428_1080-15403.xml	1907
sm_55428_1080-15682.xml	1907
sm_55428_1080-16257.xml	1907
sm_55428_1080-16364.xml	1907
sm_55428_1080-17339.xml	1907
sm_55428_1080-18145.xml	1909
sm_55428_1080-18532.xml	1907
sm_55428_1080-18604.xml	1907
sm_55428_1080-19160.xml	1907
sm_55428_1080-19251.xml	1907
sm_55428_1080-19455.xml	

sm_55428_1100-17931.xml	1920
sm_55428_1100-17938.xml	1920
sm_55428_1100-1801.xml	1914
sm_55428_1100-18173.xml	1914
sm_55428_1100-18193.xml	1915
sm_55428_1100-18211.xml	1915
sm_55428_1100-18467.xml	1915
sm_55428_1100-18593.xml	1915
sm_55428_1100-18646.xml	1915
sm_55428_1100-1890.xml	1915
sm_55428_1100-19074.xml	1914
sm_55428_1100-19270.xml	1916
sm_55428_1100-19281.xml	1915
sm_55428_1100-19507.xml	1915
sm_55428_1100-19922.xml	1915
sm_55428_1100-20021.xml	1914
sm_55428_1100-20234.xml	1914
sm_55428_1100-20491.xml	1914
sm_55428_1100-20688.xml	1914
sm_55428_1100-20958.xml	1914
sm_55428_1100-21043.xml	1914
sm_55428_1100-21092.xml	1914
sm_55428_1100-21148.xml	1917
sm_55428_1100-21234.xml	1917
sm_55428_1100-2125.xml	1915
sm_55428_1100-21369.xml	1915
sm_55428_1100-21452.xml	1915
sm_55428_1100-21454.xml	1915
sm_55428_1100-21579.xml	1920
sm_55428_1100-21680.xml	1920
sm_55428_1100-21720.xml	1920
sm_55428_1100-21725.xml	1916
sm_55428_1100-21753.xml	1916
sm_55428_1100-21813.xml	1916
sm_55428_1100-218

sm_55428_1106-16391.xml	1916
sm_55428_1106-16545.xml	1916
sm_55428_1106-16666.xml	1916
sm_55428_1106-16694.xml	1916
sm_55428_1106-16772.xml	1921
sm_55428_1106-16956.xml	1921
sm_55428_1106-17069.xml	1921
sm_55428_1106-17231.xml	1921
sm_55428_1106-17295.xml	1920
sm_55428_1106-17399.xml	1920
sm_55428_1106-17439.xml	1916
sm_55428_1106-1768.xml	1916
sm_55428_1106-17904.xml	1916
sm_55428_1106-17932.xml	1916
sm_55428_1106-17952.xml	1916
sm_55428_1106-17998.xml	1915
sm_55428_1106-180.xml	1915
sm_55428_1106-18037.xml	1915
sm_55428_1106-18141.xml	1915
sm_55428_1106-18531.xml	1915
sm_55428_1106-18774.xml	1915
sm_55428_1106-19071.xml	1916
sm_55428_1106-19091.xml	1914
sm_55428_1106-19101.xml	1914
sm_55428_1106-19196.xml	1914
sm_55428_1106-19204.xml	1914
sm_55428_1106-19247.xml	1914
sm_55428_1106-19821.xml	1914
sm_55428_1106-19861.xml	1914
sm_55428_1106-19895.xml	1914
sm_55428_1106-20125.xml	1914
sm_55428_1106-20196.xml	1914
sm_55428_1106-20197.xml	1920
sm_55428_1106-20309.xml	1920
sm_55428_1106-206

sm_55428_1113-4492.xml	1921
sm_55428_1113-45530.xml	1922
sm_55428_1113-46386.xml	1920
sm_55428_1113-46696.xml	1920
sm_55428_1113-46946.xml	1922
sm_55428_1113-47037.xml	1922
sm_55428_1113-4714.xml	1922
sm_55428_1113-47175.xml	1922
sm_55428_1113-47190.xml	1922
sm_55428_1113-47221.xml	1921
sm_55428_1113-47763.xml	1916
sm_55428_1113-48291.xml	1921
sm_55428_1113-48679.xml	1922
sm_55428_1113-49114.xml	1920
sm_55428_1113-4927.xml	1920
sm_55428_1113-4929.xml	1921
sm_55428_1113-49715.xml	1921
sm_55428_1113-49904.xml	1922
sm_55428_1113-5082.xml	1922
sm_55428_1113-57.xml	1922
sm_55428_1113-5815.xml	1922
sm_55428_1113-6272.xml	1922
sm_55428_1113-629.xml	1922
sm_55428_1113-6457.xml	1922
sm_55428_1113-6813.xml	1922
sm_55428_1113-6935.xml	1922
sm_55428_1113-7368.xml	1921


sm_55428_1113-7368.xml	1921


sm_55428_1113-7368.xml	1921
sm_55428_1113-7585.xml	1921
sm_55428_1113-7709.xml	1921
sm_55428_1113-7831.xml	1916
sm_55428_1113-7939.xml	1916
sm_55428_1113-810.xml	1916
sm_55428_1113-8654.xml	1916
sm_554

In [22]:
years

{1859: 61,
 1860: 78,
 1861: 65,
 1858: 26,
 1862: 165,
 1857: 5,
 1864: 33,
 1865: 52,
 1866: 31,
 1863: 51,
 1867: 46,
 1868: 37,
 1869: 25,
 1870: 29,
 1871: 78,
 1873: 84,
 1872: 88,
 1875: 106,
 1874: 93,
 1876: 80,
 1877: 117,
 1878: 94,
 1879: 118,
 1880: 108,
 1881: 104,
 1882: 142,
 1883: 119,
 1884: 95,
 1885: 68,
 1886: 76,
 1887: 107,
 1888: 70,
 1889: 101,
 1890: 169,
 1891: 150,
 1892: 114,
 1893: 112,
 1894: 149,
 1895: 160,
 1897: 155,
 1900: 316,
 1896: 49,
 1898: 444,
 1899: 330,
 1901: 233,
 1902: 191,
 1903: 139,
 1905: 244,
 1904: 307,
 1907: 73,
 1906: 110,
 1909: 27,
 1910: 16,
 1908: 40,
 1911: 18,
 1912: 36,
 1913: 109,
 1915: 491,
 1914: 506,
 1916: 558,
 1920: 633,
 1917: 206,
 1921: 516,
 1922: 375,
 1918: 7}

In [23]:
# sorted keys
for key, value in sorted(years.items(), key=lambda x: x[0]): 
    print("{} : {}".format(key, value))

1857 : 5
1858 : 26
1859 : 61
1860 : 78
1861 : 65
1862 : 165
1863 : 51
1864 : 33
1865 : 52
1866 : 31
1867 : 46
1868 : 37
1869 : 25
1870 : 29
1871 : 78
1872 : 88
1873 : 84
1874 : 93
1875 : 106
1876 : 80
1877 : 117
1878 : 94
1879 : 118
1880 : 108
1881 : 104
1882 : 142
1883 : 119
1884 : 95
1885 : 68
1886 : 76
1887 : 107
1888 : 70
1889 : 101
1890 : 169
1891 : 150
1892 : 114
1893 : 112
1894 : 149
1895 : 160
1896 : 49
1897 : 155
1898 : 444
1899 : 330
1900 : 316
1901 : 233
1902 : 191
1903 : 139
1904 : 307
1905 : 244
1906 : 110
1907 : 73
1908 : 40
1909 : 27
1910 : 16
1911 : 18
1912 : 36
1913 : 109
1914 : 506
1915 : 491
1916 : 558
1917 : 206
1918 : 7
1920 : 633
1921 : 516
1922 : 375


In [ ]:
# sorted values
for key, value in sorted(years.items(), key=lambda x: x[1]): 
    print("{} : {}".format(key, value))

In [24]:
t=0
f=0

for file in files:
    if is_censorship(files[file][0]):
        
        t+=1
    else:
        f+=1
print("true = ", t, "false = ", f)

NameError: name 'files' is not defined

In [ ]:
# is_censorship(files[""])

In [ ]:
nlp = spacy.load("en")

In [ ]:
# we add some words to the stop word list
for file in files:
    article = []
    doc = nlp(files[file][0].lower())
    for w in doc:
        # if it's not a stop word or punctuation mark, add it to our article!
        if not w.is_stop and not w.is_punct and not w.like_num and w.text != 'I' and not '&' in w.text and not ';' in w.text and not '$' in w.text and len(w.text) > 2 and not ' ' in w.text and not "apos" in w.text and not "quot" in w.text:
            # we add the lematized version of the word
            article.append(w.lemma_)
    files[file].append(article)

In [ ]:
# stop word list changelog
# 12/2: added "apos" and "quot" as undesirable remnants of .xml punctuation codings

Now that we have our dirty corpus, let us now clean it.

## Clean Corpus

We will clean it by removing stop words, lemmatizing, removing punctuation, numbers, spaces, bullshit.

In [ ]:
# iterate through corpus, clean code

In [ ]:
from gensim.corpora import Dictionary
import gensim
from gensim.models import CoherenceModel, LdaModel, LsiModel, HdpModel

In [ ]:
cleaned_texts = []

In [ ]:
for file in files:
    cleaned_texts.append(files[file][3])

In [ ]:
bigram = gensim.models.Phrases(cleaned_texts)

In [ ]:
texts = [bigram[line] for line in cleaned_texts]

In [ ]:
dictionary = Dictionary(texts)
corpus = [dictionary.doc2bow(text) for text in texts]

In [ ]:
ldamodel = LdaModel(corpus=corpus, num_topics=2, id2word=dictionary)

In [ ]:
ldamodel.show_topics()

Now that we have our cleaned corpus, we now sort it by month, and by year, and by decade. We can also have one for total corpus.
Now compare!

#### project outline

1. Reduce corpus to only relevant files (note: 'corpus' from now on will refer to this reduced, relevant corpus') which contain a list of keywords (e.g., censorship, ban, suppress; potentially only 'censorship' as relates to semantic/discourse analysis of a particular term and its employment and movement)
2. We will then clean the code, removing all unnecessary information and only keeping important information held in the files. For example, we will keep the FullText section, publication date, possibly the title (and subtitle).
3. Make code that chronologically orders the corpus. There is a numeric publication date that might be easier to follow. Or, for the alpha pub date: Each file is dated in the style of, for example, "May 20, 1892". We need code that can acknowledge these dates as ordered; May is after April and before June, May 20 is before May 21 and after May 19, May 20, 1892 is before May 20, 1893 and after May 20, 1891, etc.)
4. From here, we will process the chronologically-ordered and -recognized corpus in such a way that we can find latent features in the corpus:
    
    a. We can do this for the entire corpus to see if a continued latent theme (or set of themes) appears to see if 'censorship' itself has, from 1857 to 1922, contained a theme we did not expect.
    
    b. We can do this for time segments (which I refer to as the 'episteme model') whereby we segment the dates and THEN find latent features for each individual segment. What are the (unexpected) themes to be found in certain time periods? We can then cross-reference this with secondary/tertiary sources produced by historians to see what is happenening during these periods of time.
        Ex.1 We can segment periods arbitrarily, such as
                Period 1 = 1857-1876
                Period 2 = 1877-1896
                Period 3 = 1897-1916
                Period 4 = 1916-1922
        Ex.2 We can segment periods which align with major events, such as
                Period 1 = Civil War
                Period 2 = Post-Civil War
                Period 3 = World War 1
                Period 4 = Film Industry emerges
        Ex.3 We can have OVERLAPS between time segments rather than cutting them off from one another. 
                Period 1 = Civil War AND Post-Civil War
                Period 2 = Post-Civil War AND World War 1
                Period 3 = World War 1 AND Film Industry emerges
             This could be done, say, in addition to Ex.1 or Ex.2 so that a) through Ex.1 or Ex.2 we can see what changes between periods and b) through Ex.3 we can see what CONTINUES between those segments.
     c. 